# 회귀분석 심화 및 기본가정 {#regression}



> * simple regression analysis
>     + 단순회귀분석의 개념
>     + 최소자승법을 이용한 회귀계수 도출
>     + 회귀분석의 설명력 및 적합도 분석
>     + 단순회귀분석 r 실습
>
> * multiple regression analysis
>     + 다중회귀분석의 개념
>     + 다중회귀분석의 회귀계수 도출
>     + 더미변수를 활용한 다중회귀분석과 해석
>     + 다중회귀분석 r 실습
>
> * 회귀분석의 기본가정
>     + 선형성
>     + 정규성
>     + 등분산성
>     + 독립성
>     + 다중공선성
>     + 극단치 탐지
>     + 회귀분석 기본가정 r 실습



## simple regression anlysis

### 단순회귀분석의 개념
### 최소자승법을 활용한 회귀계수 도출

how to find appropiate intercept(a) and slope(b)?

$y_{i}=a+bx_{i}+e_{i}$

$\hat{y_{i}}=a+bx_{i}$

$e_{i}=y-\hat{y}$

위의 잔차를 최소화하기 위해서는 잔차의 제곱합을 최소화해야한다.

$minimize\; \sum_{i=1}^{n}{e_{i}}^2$

$\sum(y_{i}-\hat{y_{i}}^2)=\sum(y_{i}-a-bx_{i})^2$

minimize를 위해 위의 함수를 각각 a와 b로 미분하여 0이 되는 값을 구한다.

a로 미분하면 다음과 같다. 

$\frac{dF}{da}=-2\sum(y_{i}-a-bx_{i})=0$

$\sum y_{i}-an-b \sum x_{i}=0$

n으로 전체를 나눠주면

$\bar{y}-a-b\bar{x}=0$

$a=\bar{y}-b\bar{x}$

따라서 위의 식에서 회귀식은 $\bar{x}$와 $\bar{y}$를 지난다는 것을 알 수 있다. 

b로 미분하면 다음과 같다.

$\frac{df}{db}=-2\sum (y_{i}-a-bx_{i})x_{i}=0$

$y=(f(x))^n$를 미분하면 ${y}'=n({f(x)})^{n-1}\cdot {f}'(x)$ 을 기억!

$\sum x_{i}(y_{i}-a-bx_{i})=0$

$\sum x_{i}y_{i}-a\sum x_{i} - b\sum x_{i}^2 =0$

$\sum x_{i}y_{i}-(\bar{y}-b\bar{x})\sum x_{i} - b\sum x_{i}^2 =0$

$\sum x_{i}y_{i}-\bar{y}\sum x_{i} = b\sum x_{i}^2-b\bar{x}\sum x_{i}$

좌변을 먼저 정리하면 $\sum x_{i}=n\cdot \bar{x}$ 이므로

$\sum x_{i}y_{i}-n\bar{x}\bar{y} = b\sum x_{i}^2-b\bar{x}\sum x_{i}$

이를 n으로 먼저 나누면

$\frac{\sum x_{i}y_{i}}{n}-\bar{x}\bar{y}=b(\frac{\sum x_{i}^2}{n}-\frac{(\sum x_{i})^2}{n^2})$

$\frac{\sum x_{i}y_{i}}{n}-\bar{x}\bar{y}=b(\frac{\sum x_{i}^2}{n}-(\frac{(\sum x_{i})}{n})^2)$

정리를 위해 var(x)에 대한 새로운 식을 가져온다.

$var(x)=\frac{\sum(x_{i}-\bar{x})^2}{n}=\frac{\sum(x_{i})^2-2\bar{x}\sum x_{i}+n(\bar{x})^2}{n}=\frac{\sum (x_{i})^2}{n}-2\bar{x}\frac{\sum x_{i}}{n}+(\bar{x})^2=\frac{\sum (x_{i})^2}{n}-(\bar{x})^2$

이식으로 우변을 정리해보면

$\frac{\sum x_{i}y_{i}}{n}-\bar{x}\bar{y}=b(\frac{\sum x_{i}^2}{n}-(\bar{x})^2)=b\cdot (SDx)^2$

좌변을 정리하기 위해서는 $cov(x,y)$에 대한 식을 다음과 같이 변형한다. 

$Cov(X,Y)=E((X-EX)(Y-EY))=E[XY-X(EY)-(EX)Y+(EX)(EY)]=E[XY]-(EX)(EY)-(EX)(EY)+(EX)(EY)=E[XY]-(EX)(EY)$

$Cov(X,Y)=\left ( \frac{\sum x_{i}y_{i}}{n}-\bar{x}\bar{y} \right )$

이를 활용하여 좌변을 정리하면 다음과 같다. 

$Cov(x,y)=b\cdot (SD_{x})^2$

$b=\frac{Cov(x,y))}{(SD_{x})^2}=\frac{\sum (x_{i}-\bar{x})(y_{i}-\bar{y})}{\sum (x_{i}-\bar{x})^2}=Cor(x,y)\cdot \frac{SD_{y}}{SD_{x}}$


만일 x와 y를 표준화한다면 $\bar{x}$와 $\bar{y}$는 0, $SD_{x}$와 $SD_{y}$는 1이다. 

$a=\bar{y}-b\bar{x}=0$


$\therefore \hat{y}=r\cdot x$


## multiple regression analysis

### 다중회귀분석의 회귀계수 도출

#### matrix of variance and covariane

다음의 두개의 변인($X_{1}$, $X_{2}$)가 각각 3개의 관측치를 갖고 있다고 생각해보자


X1            |X2         
--------------|---------------
1             | 1  
2             | 4
2             | 7
mean of X1=2  | mean of X2=4


$\underset{Deviation scores}{X_{d}}=\overset{X}{\begin{bmatrix}
1 & 1\\ 
3 & 4\\ 
2 & 7
\end{bmatrix}}-\overset{\bar{X}}{\begin{bmatrix}
 2& 4\\ 
 2& 4\\ 
 2& 4
\end{bmatrix}}=\begin{bmatrix}
-1 & -3\\ 
 1&0 \\ 
 0&3
\end{bmatrix}$

$\underset{transpose of X_{d}}{{X_{d}}'}=\begin{bmatrix}
-1 & 1 & 0\\ 
-3 & 0 & 3
\end{bmatrix}$


$\underset{Sums\, of\, sqaures\, and\, crossproducts}{SSCP}=\overset{{X_{d}}'}{\begin{bmatrix}
-1 & -1 & 0\\ 
-3 & 0 & 3
\end{bmatrix}}\times \overset{X_{d}}{\begin{bmatrix}
-1 & -3\\ 
1 &0 \\ 
0 &3 
\end{bmatrix}}=\begin{bmatrix}
ss_{11} & ss_{12}\\ 
ss_{21} & ss_{22}
\end{bmatrix}=\begin{bmatrix}
2 &3 \\ 
3 &18 
\end{bmatrix}$

because

$SS_{11}=(-1)^2+1^2+0^2=2$

$SS_{22}=(-3)^2+0^2+3^2=18$

$SS_{12}=SS_{21}=(-1)(-3)+(1)(0)+(0)(3)=3$

$S=\frac{SSCP}{n-1}=\frac{1}{2}\begin{bmatrix}
2 & 3\\ 
3 & 18
\end{bmatrix}=\begin{bmatrix}
1 & 1.5\\ 
1.5 & 9
\end{bmatrix}=\begin{bmatrix}
variance\, of \, X_{1} & covariance\\ 
 covariance&variance\, of\, X_{2} 
\end{bmatrix}$

이처럼 $X_{d}$와 ${X_{d}}^T$의 곱은 $X_{1}$과 $X_{n}$의 분산과 공분산의 행렬로 표현됨을 알 수 있다. 

#### multiple regression의 회귀계수(beta) 계산 

다중회귀분석은 2개 이상의 변수가 동시에 계산되어야 하기 때문에 회귀식이 행렬로 표현된다. 예를 들어 우리가 아래와 같은 1개의 종속변수, 2개의 독립변수를 가지고 회귀식을 다음과 같이 구성했다고 생각해보자. 


y   |X1  |X2      
----|----|----
4   | 1  | 3
5   | 4  | 4
6   | 7  | 8
8   | 8  | 9

$y_{i}=\beta_{0}+\beta_{1}x_{1}+\beta_{2}x_{2}+e_{i}$

각 데이터를 위의 회귀식에 넣어보면 총 4개의 식이 생긴다

$y_{1}=4=1\cdot \beta_{0}+1\cdot \beta_{1}+3\cdot \beta_{2}+e_{1}$

$y_{2}=5=1\cdot \beta_{0}+4\cdot \beta_{1}+4\cdot \beta_{2}+e_{2}$

$y_{3}=6=1\cdot \beta_{0}+7\cdot \beta_{1}+8\cdot \beta_{2}+e_{3}$

$y_{4}=8=1\cdot \beta_{0}+8\cdot \beta_{1}+9\cdot \beta_{2}+e_{4}$

이는 다음과 같은 행렬로 표현할 수 있다. 

$y=\begin{bmatrix}
4\\ 
5\\ 
6\\8 
\end{bmatrix}=
\overset{X}{\begin{bmatrix}
1 & 1 & 3\\ 
1 &4  & 4\\ 
1 &7  & 8\\ 
1& 8 & 9
\end{bmatrix}}\overset{\beta}{\begin{bmatrix}
\beta_{0}\\ 
\beta_{1}\\ 
\beta_{2}
\end{bmatrix}}+\overset{e}{\begin{bmatrix}
e_{1}\\ 
e_{2}\\ 
e_{3}\\ 
e_{4}
\end{bmatrix}}$

$y=X\beta+e$

회귀계수인 $\beta$행렬의 해를 찾기 위해서는 단순회귀와 마찬가지로 잔차(e)의 제곱합을 최소화하는 $\beta$행렬을 찾아야 한다. 

잔차제곱합은 다음과 같이 transpose 행렬을 곱해줌으로서 간단히 만들 수 있다
$e^Te=(y-X\beta)^T(y-X\beta)$

note that 
$e^Te=\begin{bmatrix}
e_{1} & e_{2} & e_{3}
\end{bmatrix}\begin{bmatrix}
e_{1}\\ 
e_{2}\\ 
e_{3}
\end{bmatrix}={e_{1}}^2+{e_{2}}^2+{e_{3}}^2$

잔차제곱합은 2차 함수이기 때문에 최소값은 beta로 미분한값이 0인 지점을 찾으면 된다.(convex 형태의 2차함수를 생각해보면 기울기가 0인 지점이 y의 최소값임을 기억하자!)

잔차제곱합을 미분하기 위해서는 아래의 두개의 공식을 이해해야 한다. 

$\frac{\partial a^T\beta}{\partial \beta}=a$

$\frac{\partial \beta^TA\beta}{\partial \beta}=(A+A^T)\beta=2A\beta (when\: A\: is\: symmetric)$

잔차 제곱합을 beta로 미분한 값이 0일때의 beta값을 찾아보면 다음과 같다. 

$\frac{\partial L}{\partial\beta}=\frac{\partial}{\partial \beta}(y-X\beta)^T(y-X\beta)=\frac{\partial}{\partial \beta} (y^Ty-y^TX\beta-(X\beta)^Ty+(X\beta)^TX\beta)=\frac{\partial}{\partial \beta} (y^Ty-y^TX\beta-\beta^TX^Ty+\beta^TX^TX\beta)=0-X^Ty-X^Ty+2X^TXB=0$

좌변과 우변으로 정리하면

$X^TX\beta=X^Ty$

$\beta=(X^TX)^{-1}X^Ty$
