<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Chapter 8 직관으로 이해하는 회귀분석 | R을 활용한 산업인력개발통계</title>
  <meta name="description" content="This book is an ongoing work in progress. It is intended for use only as material for the Department of Vocational Education and Workforce Development at Seoul National University. Any other use is prohibited." />
  <meta name="generator" content="bookdown 0.48 and GitBook 2.6.7" />

  <meta property="og:title" content="Chapter 8 직관으로 이해하는 회귀분석 | R을 활용한 산업인력개발통계" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="This book is an ongoing work in progress. It is intended for use only as material for the Department of Vocational Education and Workforce Development at Seoul National University. Any other use is prohibited." />
  <meta name="github-repo" content="rstudio/bookdown-demo" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Chapter 8 직관으로 이해하는 회귀분석 | R을 활용한 산업인력개발통계" />
  
  <meta name="twitter:description" content="This book is an ongoing work in progress. It is intended for use only as material for the Department of Vocational Education and Workforce Development at Seoul National University. Any other use is prohibited." />
  

<meta name="author" content="Su Jung Choi (Seoul National University)" />


<meta name="date" content="2026-09-14" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="correlation.html"/>
<link rel="next" href="regression.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>


<style type="text/css">
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./"> Intuitive Regression Analysis in Workforce Development</a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="intro.html"><a href="intro.html"><i class="fa fa-check"></i><b>1</b> Introduction</a>
<ul>
<li class="chapter" data-level="1.1" data-path="intro.html"><a href="intro.html#r%EC%9D%84-%EC%99%9C-%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC%ED%95%A0%EA%B9%8C"><i class="fa fa-check"></i><b>1.1</b> R을 왜 사용해야할까?</a></li>
<li class="chapter" data-level="1.2" data-path="intro.html"><a href="intro.html#%EC%9D%B4-%EC%B1%85%EC%9D%98-%EA%B5%AC%EC%84%B1"><i class="fa fa-check"></i><b>1.2</b> 이 책의 구성</a>
<ul>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#%EB%B6%80.-r%EC%9D%98-%EA%B8%B0%EC%B4%88-%EC%9D%B4%ED%95%B4"><i class="fa fa-check"></i>1부. R의 기초 이해</a></li>
<li class="chapter" data-level="" data-path="intro.html"><a href="intro.html#%EB%B6%80.-r%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-%EA%B8%B0%EC%B4%88-%EB%8B%A4%EB%B3%80%EB%9F%89-%EB%B6%84%EC%84%9D"><i class="fa fa-check"></i>2부. R을 활용한 기초 다변량 분석</a></li>
</ul></li>
<li class="chapter" data-level="1.3" data-path="intro.html"><a href="intro.html#%EB%B0%B0%EC%9A%B0%EC%A7%80-%EC%95%8A%EB%8A%94-%EB%82%B4%EC%9A%A9%EB%93%A4"><i class="fa fa-check"></i><b>1.3</b> 배우지 않는 내용들</a></li>
<li class="chapter" data-level="1.4" data-path="intro.html"><a href="intro.html#%EB%8B%B9%EB%B6%80%EC%9D%98-%EB%A7%90"><i class="fa fa-check"></i><b>1.4</b> 당부의 말</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="data.html"><a href="data.html"><i class="fa fa-check"></i><b>2</b> R 자료 구조의 이해</a>
<ul>
<li class="chapter" data-level="2.1" data-path="data.html"><a href="data.html#%EB%AA%85%EB%A0%B9%EC%96%B4%EC%9D%98-%EA%B5%AC%EC%A1%B0%EC%99%80-%EC%9E%90%EB%A3%8C-%EC%9E%85%EB%A0%A5"><i class="fa fa-check"></i><b>2.1</b> 명령어의 구조와 자료 입력</a></li>
<li class="chapter" data-level="2.2" data-path="data.html"><a href="data.html#r%EC%97%90%EC%84%9C-%EC%93%B0%EC%9D%B4%EB%8A%94-%EC%9E%90%EB%A3%8C%EC%9D%98-%EC%9C%A0%ED%98%95"><i class="fa fa-check"></i><b>2.2</b> R에서 쓰이는 자료의 유형</a></li>
<li class="chapter" data-level="2.3" data-path="data.html"><a href="data.html#r%EC%97%90%EC%84%9C-%EC%93%B0%EC%9D%B4%EB%8A%94-%EC%9E%90%EB%A3%8C%EC%9D%98-%EA%B5%AC%EC%A1%B0"><i class="fa fa-check"></i><b>2.3</b> R에서 쓰이는 자료의 구조</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="data.html"><a href="data.html#%EC%8A%A4%EC%B9%BC%EB%9D%BC-scala"><i class="fa fa-check"></i><b>2.3.1</b> 스칼라 scala</a></li>
<li class="chapter" data-level="2.3.2" data-path="data.html"><a href="data.html#%EB%B2%A1%ED%84%B0-vector"><i class="fa fa-check"></i><b>2.3.2</b> 벡터 vector</a></li>
<li class="chapter" data-level="2.3.3" data-path="data.html"><a href="data.html#%EB%A7%A4%ED%8A%B8%EB%A6%AD%EC%8A%A4-matrix"><i class="fa fa-check"></i><b>2.3.3</b> 매트릭스 matrix</a></li>
<li class="chapter" data-level="2.3.4" data-path="data.html"><a href="data.html#%EB%B0%B0%EC%97%B4-array"><i class="fa fa-check"></i><b>2.3.4</b> 배열 array</a></li>
<li class="chapter" data-level="2.3.5" data-path="data.html"><a href="data.html#%EB%8D%B0%EC%9D%B4%ED%84%B0%ED%94%84%EB%A0%88%EC%9E%84-dataframe"><i class="fa fa-check"></i><b>2.3.5</b> 데이터프레임 dataframe</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="data.html"><a href="data.html#factor-%EB%B3%80%EC%88%98"><i class="fa fa-check"></i><b>2.4</b> factor 변수</a></li>
<li class="chapter" data-level="2.5" data-path="data.html"><a href="data.html#na%EC%99%80-null"><i class="fa fa-check"></i><b>2.5</b> NA와 NULL</a></li>
<li class="chapter" data-level="2.6" data-path="data.html"><a href="data.html#r-%EB%82%B4%EC%9E%A5%ED%95%A8%EC%88%98%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%EB%9F%89-%EC%82%B0%EC%B6%9C"><i class="fa fa-check"></i><b>2.6</b> R 내장함수를 활용한 기술통계량 산출</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="literature.html"><a href="literature.html"><i class="fa fa-check"></i><b>3</b> 데이터 전처리</a>
<ul>
<li class="chapter" data-level="3.1" data-path="literature.html"><a href="literature.html#%EB%93%A4%EC%96%B4%EA%B0%80%EB%A9%B0"><i class="fa fa-check"></i><b>3.1</b> 들어가며</a>
<ul>
<li class="chapter" data-level="3.1.1" data-path="literature.html"><a href="literature.html#%ED%8C%A8%ED%82%A4%EC%A7%80-%EC%A4%80%EB%B9%84%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.1.1</b> 패키지 준비하기</a></li>
<li class="chapter" data-level="3.1.2" data-path="literature.html"><a href="literature.html#%EC%9E%91%EC%97%85%EA%B3%B5%EA%B0%84-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.1.2</b> 작업공간 설정하기</a></li>
<li class="chapter" data-level="3.1.3" data-path="literature.html"><a href="literature.html#%EB%8D%B0%EC%9D%B4%ED%84%B0-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0"><i class="fa fa-check"></i><b>3.1.3</b> 데이터 불러오기</a></li>
</ul></li>
<li class="chapter" data-level="3.2" data-path="literature.html"><a href="literature.html#dplyr-%ED%8C%A8%ED%82%A4%EC%A7%80%EC%9D%98-%EC%9D%B4%ED%95%B4"><i class="fa fa-check"></i><b>3.2</b> dplyr 패키지의 이해</a>
<ul>
<li class="chapter" data-level="3.2.1" data-path="literature.html"><a href="literature.html#chain-operator"><i class="fa fa-check"></i><b>3.2.1</b> chain operator</a></li>
</ul></li>
<li class="chapter" data-level="3.3" data-path="literature.html"><a href="literature.html#dplyr%EC%9D%98-%EC%A3%BC%EC%9A%94-%EA%B8%B0%EB%8A%A5"><i class="fa fa-check"></i><b>3.3</b> dplyr의 주요 기능</a>
<ul>
<li class="chapter" data-level="3.3.1" data-path="literature.html"><a href="literature.html#filter"><i class="fa fa-check"></i><b>3.3.1</b> filter</a></li>
<li class="chapter" data-level="3.3.2" data-path="literature.html"><a href="literature.html#select"><i class="fa fa-check"></i><b>3.3.2</b> select</a></li>
<li class="chapter" data-level="3.3.3" data-path="literature.html"><a href="literature.html#arrange"><i class="fa fa-check"></i><b>3.3.3</b> arrange</a></li>
<li class="chapter" data-level="3.3.4" data-path="literature.html"><a href="literature.html#mutate"><i class="fa fa-check"></i><b>3.3.4</b> mutate</a></li>
<li class="chapter" data-level="3.3.5" data-path="literature.html"><a href="literature.html#group_by%EC%99%80-summarise"><i class="fa fa-check"></i><b>3.3.5</b> group_by와 summarise</a></li>
</ul></li>
<li class="chapter" data-level="3.4" data-path="literature.html"><a href="literature.html#%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%B0%ED%95%A9%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.4</b> 데이터 결합하기</a>
<ul>
<li class="chapter" data-level="3.4.1" data-path="literature.html"><a href="literature.html#bind_cols%EC%99%80-bind_rows%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%B0%ED%95%A9%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.4.1</b> bind_cols와 bind_rows로 데이터 결합하기</a></li>
<li class="chapter" data-level="3.4.2" data-path="literature.html"><a href="literature.html#join%EC%9C%BC%EB%A1%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%B0%ED%95%A9%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.4.2</b> join으로 데이터 결합하기</a></li>
</ul></li>
<li class="chapter" data-level="3.5" data-path="literature.html"><a href="literature.html#%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%ED%83%80%EC%9D%B4%EB%94%94%ED%95%98%EA%B2%8C-%EB%A7%8C%EB%93%A4%EA%B8%B0-pivot_longer%EC%99%80-pivot_wider"><i class="fa fa-check"></i><b>3.5</b> 데이터를 타이디하게 만들기 : pivot_longer와 pivot_wider</a>
<ul>
<li class="chapter" data-level="3.5.1" data-path="literature.html"><a href="literature.html#%EA%B8%B8%EA%B2%8C-%EB%A7%8C%EB%93%A4%EA%B8%B0-pivot_longer-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.5.1</b> 길게 만들기 : pivot_longer 활용하기</a></li>
<li class="chapter" data-level="3.5.2" data-path="literature.html"><a href="literature.html#%EB%84%93%EA%B2%8C-%EB%A7%8C%EB%93%A4%EA%B8%B0-pivot_wider-%ED%99%9C%EC%9A%A9%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>3.5.2</b> 넓게 만들기 : pivot_wider 활용하기</a></li>
</ul></li>
<li class="chapter" data-level="3.6" data-path="literature.html"><a href="literature.html#%ED%8C%A8%EB%84%90%EB%8D%B0%EC%9D%B4%ED%84%B0%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%9C-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EC%A0%84%EC%B2%98%EB%A6%AC-%EC%8B%A4%EC%8A%B5"><i class="fa fa-check"></i><b>3.6</b> 패널데이터를 활용한 데이터 전처리 실습</a>
<ul>
<li class="chapter" data-level="3.6.1" data-path="literature.html"><a href="literature.html#%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9D%98-%EC%9D%B4%ED%95%B4"><i class="fa fa-check"></i><b>3.6.1</b> 데이터의 이해</a></li>
<li class="chapter" data-level="3.6.2" data-path="literature.html"><a href="literature.html#%EB%8D%B0%EC%9D%B4%ED%84%B0%EC%9D%98-%EB%B6%88%EB%9F%AC%EC%98%A4%EA%B8%B0import"><i class="fa fa-check"></i><b>3.6.2</b> 데이터의 불러오기(import)</a></li>
<li class="chapter" data-level="3.6.3" data-path="literature.html"><a href="literature.html#%ED%95%84%EC%9A%94%ED%95%9C-%EB%B3%80%EC%88%98%EB%A7%8C-%EC%84%A0%ED%83%9Dselect"><i class="fa fa-check"></i><b>3.6.3</b> 필요한 변수만 선택(select)</a></li>
<li class="chapter" data-level="3.6.4" data-path="literature.html"><a href="literature.html#%EA%B8%B0%EC%97%85-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%B0%ED%95%A9one-to-one-match"><i class="fa fa-check"></i><b>3.6.4</b> 기업 데이터 결합(one-to-one match)</a></li>
<li class="chapter" data-level="3.6.5" data-path="literature.html"><a href="literature.html#%EA%B7%BC%EB%A1%9C%EC%9E%90-%EA%B8%B0%EC%97%85-%EB%8D%B0%EC%9D%B4%ED%84%B0-%EA%B2%B0%ED%95%A9one-to-many-match"><i class="fa fa-check"></i><b>3.6.5</b> 근로자-기업 데이터 결합(one-to-many match)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="4" data-path="graph.html"><a href="graph.html"><i class="fa fa-check"></i><b>4</b> 데이터 시각화</a>
<ul>
<li class="chapter" data-level="4.1" data-path="graph.html"><a href="graph.html#%EB%93%A4%EC%96%B4%EA%B0%80%EB%A9%B0-1"><i class="fa fa-check"></i><b>4.1</b> 들어가며</a></li>
<li class="chapter" data-level="4.2" data-path="graph.html"><a href="graph.html#ggplot2%EC%9D%98-%EC%84%A4%EC%B9%98-%EB%B0%8F-%EC%86%8C%EA%B0%9C"><i class="fa fa-check"></i><b>4.2</b> ggplot2의 설치 및 소개</a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="graph.html"><a href="graph.html#ggplot2-%EC%84%A4%EC%B9%98"><i class="fa fa-check"></i><b>4.2.1</b> ggplot2 설치</a></li>
<li class="chapter" data-level="4.2.2" data-path="graph.html"><a href="graph.html#ggplot2%EC%9D%98-%EC%9E%91%EB%8F%99-%EC%9B%90%EB%A6%AC"><i class="fa fa-check"></i><b>4.2.2</b> ggplot2의 작동 원리</a></li>
<li class="chapter" data-level="4.2.3" data-path="graph.html"><a href="graph.html#%EB%B3%80%EC%88%98%EC%9D%98-%EA%B0%9C%EC%88%98-%EC%9C%A0%ED%98%95%EA%B3%BC-%EA%B7%B8%EB%9E%98%ED%94%84-%EC%A2%85%EB%A5%98"><i class="fa fa-check"></i><b>4.2.3</b> 변수의 개수, 유형과 그래프 종류</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="graph.html"><a href="graph.html#%EB%B3%80%EC%9D%B8%EC%9D%B4-1%EA%B0%9C%EC%9D%B8-graph"><i class="fa fa-check"></i><b>4.3</b> 변인이 1개인 graph</a>
<ul>
<li class="chapter" data-level="4.3.1" data-path="graph.html"><a href="graph.html#%EB%B3%80%EC%9D%B8%EC%9D%B4-%EC%97%B0%EC%86%8D%ED%98%95continuous%EC%9D%B8-%EA%B2%BD%EC%9A%B0"><i class="fa fa-check"></i><b>4.3.1</b> 변인이 연속형(continuous)인 경우</a></li>
</ul></li>
<li class="chapter" data-level="4.4" data-path="graph.html"><a href="graph.html#%EB%B3%80%EC%9D%B8%EC%9D%B4-2%EA%B0%9C%EC%9D%B8-graph"><i class="fa fa-check"></i><b>4.4</b> 변인이 2개인 graph</a>
<ul>
<li class="chapter" data-level="4.4.1" data-path="graph.html"><a href="graph.html#continuous-x-continuous-y"><i class="fa fa-check"></i><b>4.4.1</b> Continuous X, Continuous Y</a></li>
<li class="chapter" data-level="4.4.2" data-path="graph.html"><a href="graph.html#discrete-x-continuous-y"><i class="fa fa-check"></i><b>4.4.2</b> Discrete X, Continuous Y</a></li>
</ul></li>
<li class="chapter" data-level="4.5" data-path="graph.html"><a href="graph.html#miscellaneous-items"><i class="fa fa-check"></i><b>4.5</b> Miscellaneous items</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="probability.html"><a href="probability.html"><i class="fa fa-check"></i><b>5</b> 추론통계과 가설검정</a>
<ul>
<li class="chapter" data-level="5.1" data-path="probability.html"><a href="probability.html#%EC%B6%94%EB%A1%A0%ED%86%B5%EA%B3%84%EC%99%80-%ED%99%95%EB%A5%A0"><i class="fa fa-check"></i><b>5.1</b> 추론통계와 확률</a>
<ul>
<li class="chapter" data-level="5.1.1" data-path="probability.html"><a href="probability.html#%EA%B8%B0%EC%88%A0%ED%86%B5%EA%B3%84%EC%99%80-%EC%B6%94%EB%A1%A0%ED%86%B5%EA%B3%84"><i class="fa fa-check"></i><b>5.1.1</b> 기술통계와 추론통계</a></li>
<li class="chapter" data-level="5.1.2" data-path="probability.html"><a href="probability.html#%ED%99%95%EB%A5%A0probability%EA%B3%BC-%ED%99%95%EB%A5%A0%EB%B3%80%EC%88%98random-variable"><i class="fa fa-check"></i><b>5.1.2</b> 확률<code>probability</code>과 확률변수<code>random variable</code></a></li>
<li class="chapter" data-level="5.1.3" data-path="probability.html"><a href="probability.html#%ED%99%95%EB%A5%A0%EB%B3%80%EC%88%98random-variable%EC%99%80-%ED%99%95%EB%A5%A0%EB%B6%84%ED%8F%ACprobability-distribution"><i class="fa fa-check"></i><b>5.1.3</b> 확률변수<code>random variable</code>와 확률분포<code>probability distribution</code></a></li>
<li class="chapter" data-level="5.1.4" data-path="probability.html"><a href="probability.html#%ED%99%95%EB%A5%A0%EC%A7%88%EB%9F%89%ED%95%A8%EC%88%98%EC%99%80-%ED%99%95%EB%A5%A0%EB%B0%80%EB%8F%84%ED%95%A8%EC%88%98"><i class="fa fa-check"></i><b>5.1.4</b> 확률질량함수와 확률밀도함수</a></li>
</ul></li>
<li class="chapter" data-level="5.2" data-path="probability.html"><a href="probability.html#%EB%8C%80%ED%91%9C%EC%A0%81%EC%9D%B8-%ED%99%95%EB%A5%A0%EB%B6%84%ED%8F%AC"><i class="fa fa-check"></i><b>5.2</b> 대표적인 확률분포</a>
<ul>
<li class="chapter" data-level="5.2.1" data-path="probability.html"><a href="probability.html#%EC%A0%95%EA%B7%9C%EB%B6%84%ED%8F%AC"><i class="fa fa-check"></i><b>5.2.1</b> 정규분포</a></li>
<li class="chapter" data-level="5.2.2" data-path="probability.html"><a href="probability.html#%ED%91%9C%EC%A4%80%EC%A0%95%EA%B7%9C%EB%B6%84%ED%8F%AC-standard-normal-distribution"><i class="fa fa-check"></i><b>5.2.2</b> 표준정규분포 (standard normal distribution)</a></li>
<li class="chapter" data-level="5.2.3" data-path="probability.html"><a href="probability.html#%EC%B9%B4%EC%9D%B4%EC%8A%A4%ED%80%98%EC%96%B4%EB%B6%84%ED%8F%AC-chi-square-distribution"><i class="fa fa-check"></i><b>5.2.3</b> 카이스퀘어분포 chi-square distribution</a></li>
<li class="chapter" data-level="5.2.4" data-path="probability.html"><a href="probability.html#f-%EB%B6%84%ED%8F%AC-f-distribution"><i class="fa fa-check"></i><b>5.2.4</b> F 분포 F distribution</a></li>
</ul></li>
<li class="chapter" data-level="5.3" data-path="probability.html"><a href="probability.html#%EC%A4%91%EC%8B%AC%EA%B7%B9%ED%95%9C%EC%A0%95%EB%A6%AC"><i class="fa fa-check"></i><b>5.3</b> 중심극한정리</a>
<ul>
<li class="chapter" data-level="5.3.1" data-path="probability.html"><a href="probability.html#%ED%91%9C%EB%B3%B8%ED%8F%89%EA%B7%A0%EA%B3%BC-%ED%91%9C%EB%B3%B8%ED%8F%89%EA%B7%A0-%EB%B6%84%ED%8F%AC"><i class="fa fa-check"></i><b>5.3.1</b> 표본평균과 표본평균 분포</a></li>
<li class="chapter" data-level="5.3.2" data-path="probability.html"><a href="probability.html#%EC%98%88%EC%A0%9C%EB%A5%BC-%ED%86%B5%ED%95%B4-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EC%A4%91%EC%8B%AC%EA%B7%B9%ED%95%9C%EC%A0%95%EB%A6%AC"><i class="fa fa-check"></i><b>5.3.2</b> 예제를 통해 이해하는 중심극한정리</a></li>
<li class="chapter" data-level="5.3.3" data-path="probability.html"><a href="probability.html#%EC%8B%9C%EB%AE%AC%EB%A0%88%EC%9D%B4%EC%85%98%EC%9D%84-%ED%86%B5%ED%95%B4-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EC%A4%91%EC%8B%AC%EA%B7%B9%ED%95%9C%EC%A0%95%EB%A6%AC"><i class="fa fa-check"></i><b>5.3.3</b> 시뮬레이션을 통해 이해하는 중심극한정리</a></li>
</ul></li>
<li class="chapter" data-level="5.4" data-path="probability.html"><a href="probability.html#%EC%B6%94%EC%A0%95%EA%B3%BC-%EA%B0%80%EC%84%A4%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>5.4</b> 추정과 가설검정</a>
<ul>
<li class="chapter" data-level="5.4.1" data-path="probability.html"><a href="probability.html#%EC%B6%94%EC%A0%95"><i class="fa fa-check"></i><b>5.4.1</b> 추정</a></li>
<li class="chapter" data-level="5.4.2" data-path="probability.html"><a href="probability.html#%EC%8B%A0%EB%A2%B0%EA%B5%AC%EA%B0%84%EC%9D%98-%ED%95%B4%EC%84%9D"><i class="fa fa-check"></i><b>5.4.2</b> 신뢰구간의 해석</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="6" data-path="ttest.html"><a href="ttest.html"><i class="fa fa-check"></i><b>6</b> t검정과 ANOVA</a>
<ul>
<li class="chapter" data-level="6.1" data-path="ttest.html"><a href="ttest.html#%EB%AA%A8%EC%A7%91%EB%8B%A8-%ED%8F%89%EA%B7%A0%EC%97%90-%EA%B4%80%ED%95%9C-%EA%B0%80%EC%84%A4%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>6.1</b> 모집단 평균에 관한 가설검정</a></li>
<li class="chapter" data-level="6.2" data-path="ttest.html"><a href="ttest.html#t-%EA%B2%80%EC%A0%95-t-test"><i class="fa fa-check"></i><b>6.2</b> t 검정 (t-test)</a></li>
<li class="chapter" data-level="6.3" data-path="ttest.html"><a href="ttest.html#t-%EA%B2%80%EC%A0%95-t-test%EC%9D%98-%EA%B0%9C%EB%85%90-%EB%B0%8F-%EA%B0%80%EC%A0%95"><i class="fa fa-check"></i><b>6.3</b> t 검정 (t-test)의 개념 및 가정</a>
<ul>
<li class="chapter" data-level="6.3.1" data-path="ttest.html"><a href="ttest.html#%EB%8B%A8%EC%9D%BC-%EB%AA%A8%EC%A7%91%EB%8B%A8-%ED%8F%89%EA%B7%A0%EC%97%90-%EB%8C%80%ED%95%9C-t-%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>6.3.1</b> 단일 모집단 평균에 대한 t 검정</a></li>
<li class="chapter" data-level="6.3.2" data-path="ttest.html"><a href="ttest.html#%EB%8F%99%EC%9D%BC-%EB%AA%A8%EC%A7%91%EB%8B%A8-%EB%B0%98%EB%B3%B5%EC%B8%A1%EC%A0%95-%ED%8F%89%EA%B7%A0%EC%97%90-%EB%8C%80%ED%95%9C-t-%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>6.3.2</b> 동일 모집단 반복측정 평균에 대한 t 검정</a></li>
<li class="chapter" data-level="6.3.3" data-path="ttest.html"><a href="ttest.html#%EB%91%90-%EB%AA%A8%EC%A7%91%EB%8B%A8-%ED%8F%89%EA%B7%A0%EC%97%90-%EB%8C%80%ED%95%9C-t-%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>6.3.3</b> 두 모집단 평균에 대한 t 검정</a></li>
<li class="chapter" data-level="6.3.4" data-path="ttest.html"><a href="ttest.html#t-%EA%B2%80%EC%A0%95%EC%97%90%EC%84%9C%EC%9D%98-%ED%9A%A8%EA%B3%BC%ED%81%AC%EA%B8%B0%EC%99%80-%EA%B2%80%EC%A6%9D%EB%A0%A5"><i class="fa fa-check"></i><b>6.3.4</b> t 검정에서의 효과크기와 검증력</a></li>
<li class="chapter" data-level="6.3.5" data-path="ttest.html"><a href="ttest.html#r%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-t-%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>6.3.5</b> R을 활용한 t 검정</a></li>
</ul></li>
<li class="chapter" data-level="6.4" data-path="ttest.html"><a href="ttest.html#%EB%B6%84%EC%82%B0%EB%B6%84%EC%84%9D-anova"><i class="fa fa-check"></i><b>6.4</b> 분산분석 (ANOVA)</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="ttest.html"><a href="ttest.html#%EB%B6%84%EC%82%B0%EB%B6%84%EC%84%9D-anova%EC%9D%98-%EA%B0%9C%EB%85%90"><i class="fa fa-check"></i><b>6.4.1</b> 분산분석 (ANOVA)의 개념</a></li>
<li class="chapter" data-level="6.4.2" data-path="ttest.html"><a href="ttest.html#%EC%9D%BC%EC%9B%90%EB%B6%84%EC%82%B0%EB%B6%84%EC%84%9D-%EA%B3%B5%EC%8B%9D"><i class="fa fa-check"></i><b>6.4.2</b> 일원분산분석 공식</a></li>
<li class="chapter" data-level="6.4.3" data-path="ttest.html"><a href="ttest.html#%EC%86%90%EC%9C%BC%EB%A1%9C-%ED%92%80%EC%96%B4%EB%B3%B4%EB%8A%94-%EC%9D%BC%EC%9B%90%EB%B6%84%EC%82%B0%EB%B6%84%EC%84%9Danova"><i class="fa fa-check"></i><b>6.4.3</b> 손으로 풀어보는 일원분산분석(ANOVA)</a></li>
<li class="chapter" data-level="6.4.4" data-path="ttest.html"><a href="ttest.html#r%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-%EC%9D%BC%EC%9B%90%EB%B6%84%EC%82%B0%EB%B6%84%EC%84%9Danova"><i class="fa fa-check"></i><b>6.4.4</b> R을 활용한 일원분산분석(ANOVA)</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="correlation.html"><a href="correlation.html"><i class="fa fa-check"></i><b>7</b> 분산, 공분산 그리고 상관</a>
<ul>
<li class="chapter" data-level="7.1" data-path="correlation.html"><a href="correlation.html#%EB%91%90-%EB%B3%80%EC%88%98%EC%9D%98-%EA%B4%80%EA%B3%84"><i class="fa fa-check"></i><b>7.1</b> 두 변수의 관계</a>
<ul>
<li class="chapter" data-level="7.1.1" data-path="correlation.html"><a href="correlation.html#%EA%B4%80%EB%A0%A8-%EA%B0%80%EC%84%A4%EB%93%A4"><i class="fa fa-check"></i><b>7.1.1</b> 관련 가설들</a></li>
<li class="chapter" data-level="7.1.2" data-path="correlation.html"><a href="correlation.html#%EB%B3%80%EC%88%98%EC%9D%98-%EC%B2%99%EB%8F%84%EC%97%90-%EB%94%B0%EB%A5%B8-%EB%91%90-%EB%B3%80%EC%88%98%EC%9D%98-%EA%B4%80%EA%B3%84"><i class="fa fa-check"></i><b>7.1.2</b> 변수의 척도에 따른 두 변수의 관계</a></li>
</ul></li>
<li class="chapter" data-level="7.2" data-path="correlation.html"><a href="correlation.html#%EB%B6%84%EC%82%B0%EA%B3%BC-%EA%B3%B5%EB%B6%84%EC%82%B0"><i class="fa fa-check"></i><b>7.2</b> 분산과 공분산</a>
<ul>
<li class="chapter" data-level="7.2.1" data-path="correlation.html"><a href="correlation.html#%EB%B6%84%EC%82%B0%EC%9D%98-%EC%9D%98%EB%AF%B8"><i class="fa fa-check"></i><b>7.2.1</b> 분산의 의미</a></li>
<li class="chapter" data-level="7.2.2" data-path="correlation.html"><a href="correlation.html#%EB%91%90-%EB%B3%80%EC%88%98%EC%9D%98-%EB%B6%84%EC%82%B0-%EA%B3%B5%EB%B6%84%EC%82%B0"><i class="fa fa-check"></i><b>7.2.2</b> 두 변수의 분산, 공분산</a></li>
</ul></li>
<li class="chapter" data-level="7.3" data-path="correlation.html"><a href="correlation.html#%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98"><i class="fa fa-check"></i><b>7.3</b> 상관계수</a>
<ul>
<li class="chapter" data-level="7.3.1" data-path="correlation.html"><a href="correlation.html#%EA%B3%B5%EB%B6%84%EC%82%B0%EC%9D%98-%ED%95%9C%EA%B3%84"><i class="fa fa-check"></i><b>7.3.1</b> 공분산의 한계</a></li>
<li class="chapter" data-level="7.3.2" data-path="correlation.html"><a href="correlation.html#%EA%B3%B5%EB%B6%84%EC%82%B0%EC%9D%98-%ED%91%9C%EC%A4%80%ED%99%94%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98"><i class="fa fa-check"></i><b>7.3.2</b> 공분산의 표준화=상관계수</a></li>
<li class="chapter" data-level="7.3.3" data-path="correlation.html"><a href="correlation.html#%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98%EC%9D%98-%ED%95%B4%EC%84%9D"><i class="fa fa-check"></i><b>7.3.3</b> 상관계수의 해석</a></li>
<li class="chapter" data-level="7.3.4" data-path="correlation.html"><a href="correlation.html#%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98-%EC%B6%94%EC%A0%95-%EB%B0%8F-%EC%9C%A0%EC%9D%98%EC%84%B1-%EA%B2%80%EC%A0%95"><i class="fa fa-check"></i><b>7.3.4</b> 상관계수 추정 및 유의성 검정</a></li>
</ul></li>
<li class="chapter" data-level="7.4" data-path="correlation.html"><a href="correlation.html#%ED%8E%B8%EC%83%81%EA%B4%80%EA%B3%84%EC%88%98"><i class="fa fa-check"></i><b>7.4</b> 편상관계수</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="intuitive.html"><a href="intuitive.html"><i class="fa fa-check"></i><b>8</b> 직관으로 이해하는 회귀분석</a>
<ul>
<li class="chapter" data-level="8.1" data-path="intuitive.html"><a href="intuitive.html#%EC%82%B0%EC%97%85%EC%9D%B8%EB%A0%A5%EA%B0%9C%EB%B0%9C%EC%97%90%EC%84%9C%EC%9D%98-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D"><i class="fa fa-check"></i><b>8.1</b> 산업인력개발에서의 회귀분석</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="intuitive.html"><a href="intuitive.html#%EB%B3%80%EC%88%98%EA%B0%84%EC%9D%98-%EA%B4%80%EA%B3%84%EB%A5%BC-%EA%B5%AC%EB%AA%85%ED%95%98%EB%8A%94-%EC%97%B0%EA%B5%AC%EA%B0%80%EC%84%A4%EB%93%A4"><i class="fa fa-check"></i><b>8.1.1</b> 변수간의 관계를 구명하는 연구가설들</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EA%B3%BC-1%EC%B0%A8-%ED%95%A8%EC%88%98"><i class="fa fa-check"></i><b>8.2</b> 회귀분석과 1차 함수</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="intuitive.html"><a href="intuitive.html#%EC%A0%88%ED%8E%B8%EA%B3%BC-%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8"><i class="fa fa-check"></i><b>8.2.1</b> 절편과 기울기의 의미</a></li>
<li class="chapter" data-level="8.2.2" data-path="intuitive.html"><a href="intuitive.html#%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8"><i class="fa fa-check"></i><b>8.2.2</b> 기울기의 의미</a></li>
<li class="chapter" data-level="8.2.3" data-path="intuitive.html"><a href="intuitive.html#haty-y%EC%99%80-%EC%9E%94%EC%B0%A8residual"><i class="fa fa-check"></i><b>8.2.3</b> <span class="math inline">\(\hat{Y}\)</span>, <span class="math inline">\(Y\)</span>와 잔차(residual)</a></li>
<li class="chapter" data-level="8.2.4" data-path="intuitive.html"><a href="intuitive.html#%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EA%B0%80-%EB%91%90-%EA%B0%9C-%EC%9D%B4%EC%83%81%EC%9D%BC%EB%95%8C%EC%9D%98-%ED%9A%8C%EA%B7%80%EC%8B%9D"><i class="fa fa-check"></i><b>8.2.4</b> 독립변수가 두 개 이상일때의 회귀식</a></li>
<li class="chapter" data-level="8.2.5" data-path="intuitive.html"><a href="intuitive.html#added-variable-plot"><i class="fa fa-check"></i><b>8.2.5</b> added variable plot</a></li>
</ul></li>
<li class="chapter" data-level="8.3" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EA%B3%BC-2%EC%B0%A8%ED%95%A8%EC%88%98"><i class="fa fa-check"></i><b>8.3</b> 회귀분석과 2차함수</a>
<ul>
<li class="chapter" data-level="8.3.1" data-path="intuitive.html"><a href="intuitive.html#%EB%B9%84%EC%84%A0%ED%98%95-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D"><i class="fa fa-check"></i><b>8.3.1</b> 비선형 회귀분석</a></li>
<li class="chapter" data-level="8.3.2" data-path="intuitive.html"><a href="intuitive.html#%EC%A0%88%ED%8E%B8%EC%9D%98-%EC%9D%98%EB%AF%B8"><i class="fa fa-check"></i><b>8.3.2</b> 절편의 의미</a></li>
<li class="chapter" data-level="8.3.3" data-path="intuitive.html"><a href="intuitive.html#%EC%B0%A8%ED%95%AD%EB%B0%8F-2%EC%B0%A8%ED%95%AD%EC%9D%98-%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8"><i class="fa fa-check"></i><b>8.3.3</b> 1차항및 2차항의 기울기의 의미</a></li>
<li class="chapter" data-level="8.3.4" data-path="intuitive.html"><a href="intuitive.html#%EC%9E%84%EA%B8%88%EB%B0%A9%EC%A0%95%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EB%B9%84%EC%84%A0%ED%98%95-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D"><i class="fa fa-check"></i><b>8.3.4</b> 임금방정식으로 이해하는 비선형 회귀분석</a></li>
</ul></li>
<li class="chapter" data-level="8.4" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%97%90%EC%84%9C-%EB%8D%94%EB%AF%B8%EB%B3%80%EC%88%98-%ED%99%9C%EC%9A%A9"><i class="fa fa-check"></i><b>8.4</b> 회귀분석에서 더미변수 활용</a>
<ul>
<li class="chapter" data-level="8.4.1" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%97%90-%EC%A0%81%ED%95%A9%ED%95%9C-%EB%B3%80%EC%88%98%EC%9D%98-%EC%B2%99%EB%8F%84"><i class="fa fa-check"></i><b>8.4.1</b> 회귀분석에 적합한 변수의 척도</a></li>
<li class="chapter" data-level="8.4.2" data-path="intuitive.html"><a href="intuitive.html#%EB%B2%94%EC%A3%BC%ED%98%95-%EB%B3%80%EC%88%98%EA%B0%80-%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EB%A1%9C-%ED%88%AC%EC%9E%85%EB%90%A0-%EB%95%8C"><i class="fa fa-check"></i><b>8.4.2</b> 범주형 변수가 독립변수로 투입될 때</a></li>
</ul></li>
<li class="chapter" data-level="8.5" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EC%A1%B0%EC%A0%88%ED%9A%A8%EA%B3%BC"><i class="fa fa-check"></i><b>8.5</b> 회귀식으로 이해하는 조절효과</a>
<ul>
<li class="chapter" data-level="8.5.1" data-path="intuitive.html"><a href="intuitive.html#%EC%A1%B0%EC%A0%88%ED%9A%A8%EA%B3%BC%EC%9D%98-%EA%B0%9C%EB%85%90"><i class="fa fa-check"></i><b>8.5.1</b> 조절효과의 개념</a></li>
<li class="chapter" data-level="8.5.2" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D-%EB%A7%8C%EB%93%A4%EA%B8%B0%EC%99%80-%ED%95%B4%EC%84%9D%ED%95%98%EA%B8%B0"><i class="fa fa-check"></i><b>8.5.2</b> 회귀식 만들기와 해석하기</a></li>
<li class="chapter" data-level="8.5.3" data-path="intuitive.html"><a href="intuitive.html#%EB%B6%84%EC%84%9D%EA%B2%B0%EA%B3%BC-%ED%95%B4%EC%84%9D-%EC%98%88%EC%A0%9C"><i class="fa fa-check"></i><b>8.5.3</b> 분석결과 해석 예제</a></li>
</ul></li>
<li class="chapter" data-level="8.6" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EB%A7%A4%EA%B0%9C%ED%9A%A8%EA%B3%BC"><i class="fa fa-check"></i><b>8.6</b> 회귀식으로 이해하는 매개효과</a>
<ul>
<li class="chapter" data-level="8.6.1" data-path="intuitive.html"><a href="intuitive.html#%EB%A7%A4%EA%B0%9C%ED%9A%A8%EA%B3%BC%EC%9D%98-%EA%B0%9C%EB%85%90"><i class="fa fa-check"></i><b>8.6.1</b> 매개효과의 개념</a></li>
<li class="chapter" data-level="8.6.2" data-path="intuitive.html"><a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D-%EB%A7%8C%EB%93%A4%EA%B8%B0%EC%99%80-%ED%95%B4%EC%84%9D%ED%95%98%EA%B8%B0-1"><i class="fa fa-check"></i><b>8.6.2</b> 회귀식 만들기와 해석하기</a></li>
<li class="chapter" data-level="8.6.3" data-path="intuitive.html"><a href="intuitive.html#%EB%B6%84%EC%84%9D%EA%B2%B0%EA%B3%BC-%ED%95%B4%EC%84%9D-%EC%98%88%EC%A0%9C-1"><i class="fa fa-check"></i><b>8.6.3</b> 분석결과 해석 예제</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="regression.html"><a href="regression.html"><i class="fa fa-check"></i><b>9</b> 회귀분석 심화 및 기본가정</a>
<ul>
<li class="chapter" data-level="9.1" data-path="regression.html"><a href="regression.html#simple-regression-anlysis"><i class="fa fa-check"></i><b>9.1</b> simple regression anlysis</a>
<ul>
<li class="chapter" data-level="9.1.1" data-path="regression.html"><a href="regression.html#%EB%8B%A8%EC%88%9C%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%9D%98-%EA%B0%9C%EB%85%90"><i class="fa fa-check"></i><b>9.1.1</b> 단순회귀분석의 개념</a></li>
<li class="chapter" data-level="9.1.2" data-path="regression.html"><a href="regression.html#%EC%B5%9C%EC%86%8C%EC%9E%90%EC%8A%B9%EB%B2%95%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-%ED%9A%8C%EA%B7%80%EA%B3%84%EC%88%98-%EB%8F%84%EC%B6%9C"><i class="fa fa-check"></i><b>9.1.2</b> 최소자승법을 활용한 회귀계수 도출</a></li>
</ul></li>
<li class="chapter" data-level="9.2" data-path="regression.html"><a href="regression.html#multiple-regression-analysis"><i class="fa fa-check"></i><b>9.2</b> multiple regression analysis</a>
<ul>
<li class="chapter" data-level="9.2.1" data-path="regression.html"><a href="regression.html#%EB%8B%A4%EC%A4%91%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%9D%98-%ED%9A%8C%EA%B7%80%EA%B3%84%EC%88%98-%EB%8F%84%EC%B6%9C"><i class="fa fa-check"></i><b>9.2.1</b> 다중회귀분석의 회귀계수 도출</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="10" data-path="regression-1.html"><a href="regression-1.html"><i class="fa fa-check"></i><b>10</b> regression</a>
<ul>
<li class="chapter" data-level="10.1" data-path="regression-1.html"><a href="regression-1.html#simple-regression-anlysis-1"><i class="fa fa-check"></i><b>10.1</b> simple regression anlysis</a>
<ul>
<li class="chapter" data-level="10.1.1" data-path="regression-1.html"><a href="regression-1.html#%EB%8B%A8%EC%88%9C%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%9D%98-%EA%B0%9C%EB%85%90-1"><i class="fa fa-check"></i><b>10.1.1</b> 단순회귀분석의 개념</a></li>
<li class="chapter" data-level="10.1.2" data-path="regression-1.html"><a href="regression-1.html#%EC%B5%9C%EC%86%8C%EC%9E%90%EC%8A%B9%EB%B2%95%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-%ED%9A%8C%EA%B7%80%EA%B3%84%EC%88%98-%EB%8F%84%EC%B6%9C-1"><i class="fa fa-check"></i><b>10.1.2</b> 최소자승법을 활용한 회귀계수 도출</a></li>
</ul></li>
<li class="chapter" data-level="10.2" data-path="regression-1.html"><a href="regression-1.html#multiple-regression-analysis-1"><i class="fa fa-check"></i><b>10.2</b> multiple regression analysis</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="regression-1.html"><a href="regression-1.html#%EB%8B%A4%EC%A4%91%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%9D%98-%ED%9A%8C%EA%B7%80%EA%B3%84%EC%88%98-%EB%8F%84%EC%B6%9C-1"><i class="fa fa-check"></i><b>10.2.1</b> 다중회귀분석의 회귀계수 도출</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="" data-path="references.html"><a href="references.html"><i class="fa fa-check"></i>References</a></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">R을 활용한 산업인력개발통계</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="intuitive" class="section level1 hasAnchor" number="8">
<h1><span class="header-section-number">Chapter 8</span> 직관으로 이해하는 회귀분석<a href="intuitive.html#intuitive" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<blockquote>
<ul>
<li>산업인력개발에서의 회귀분석
<ul>
<li>변수간의 관계를 구명하는 연구가설들</li>
<li>연구가설을 검정하기위해 필요한 데이터의 구조</li>
</ul></li>
<li>회귀분석과 1차함수
<ul>
<li>절편의 의미</li>
<li>기울기의 의미</li>
<li>Y hat과 Y</li>
<li>변수가 여러개일때 계수의 해석(다중회귀분석과 통제변수)</li>
</ul></li>
<li>회귀분석과 2차함수
<ul>
<li>연구문제(임금방정식)</li>
<li>절편의 의미</li>
<li>기울기의 의미</li>
</ul></li>
<li>회귀식으로 이해하는 조절효과
<ul>
<li>조절효과의 개념</li>
<li>회귀식 만들기와 해석하기</li>
<li>분석결과 해석하기</li>
</ul></li>
<li>회귀식으로 이해하는 매개효과
<ul>
<li>매개효과의 개념</li>
<li>회귀식 만들기와 해석하기</li>
<li>분석결과 해석하기</li>
</ul></li>
</ul>
</blockquote>
<div id="산업인력개발에서의-회귀분석" class="section level2 hasAnchor" number="8.1">
<h2><span class="header-section-number">8.1</span> 산업인력개발에서의 회귀분석<a href="intuitive.html#%EC%82%B0%EC%97%85%EC%9D%B8%EB%A0%A5%EA%B0%9C%EB%B0%9C%EC%97%90%EC%84%9C%EC%9D%98-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>산업인력개발분야에서 이루어지는 상당수의 연구들은 회귀분석을 기초로 하고 있다. 회귀분석은 중급이상의 연구방법의 밑바탕이 되며, 최근 연구들에서 많이 쓰이고 있는 조절효과, 매개효과분석, 구조방정식분석, 다층모형 분석 등의 기초이다. 회귀분석에서 가장 중요한 것은 회귀식을 이해하는 것인데, 상술한 연구방법들이 모두 간단한 회귀식의 조합으로 풀어나갈 수 있기 때문이다. 이 책의 9장은 다른 장과 다르게 좀더 직관적으로 회귀분석을 설명하려고 한다.</p>
<div id="변수간의-관계를-구명하는-연구가설들" class="section level3 hasAnchor" number="8.1.1">
<h3><span class="header-section-number">8.1.1</span> 변수간의 관계를 구명하는 연구가설들<a href="intuitive.html#%EB%B3%80%EC%88%98%EA%B0%84%EC%9D%98-%EA%B4%80%EA%B3%84%EB%A5%BC-%EA%B5%AC%EB%AA%85%ED%95%98%EB%8A%94-%EC%97%B0%EA%B5%AC%EA%B0%80%EC%84%A4%EB%93%A4" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>회귀분석이란 무엇인가? 간단히 회귀분석의 특징과 목적을 설명하면 다음과 같다.
* 두 변수간의 “관계”를 분석하는 목적이 있다.
* 두 변수간의 “관계”는 수치화 하여 비교할 수 있다.</p>
</div>
</div>
<div id="회귀분석과-1차-함수" class="section level2 hasAnchor" number="8.2">
<h2><span class="header-section-number">8.2</span> 회귀분석과 1차 함수<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EA%B3%BC-1%EC%B0%A8-%ED%95%A8%EC%88%98" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="절편과-기울기의-의미" class="section level3 hasAnchor" number="8.2.1">
<h3><span class="header-section-number">8.2.1</span> 절편과 기울기의 의미<a href="intuitive.html#%EC%A0%88%ED%8E%B8%EA%B3%BC-%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>예를 들어 근로자의 ’학습시간’과 ’직무성과’가 관계가 있다고 가정해보자. 근로자 10명으로부터 작년 1년간의 학습시간과 그 해의 직무성과 자료를 다음의 표와 같이 수집하였다.</p>
<table>
<thead>
<tr class="header">
<th align="center">ID</th>
<th align="center">X(학습시간)</th>
<th align="center">Y(직무성과)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">12</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0.5</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">3</td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">3</td>
<td align="center">21</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">3.5</td>
<td align="center">18.5</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">4</td>
<td align="center">21.5</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">4</td>
<td align="center">23.5</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">4.5</td>
<td align="center">22.5</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">5</td>
<td align="center">25</td>
</tr>
</tbody>
</table>
<p><img src="_main_files/figure-html/figures-side-1.png" alt="" width="50%" /><img src="_main_files/figure-html/figures-side-2.png" alt="" width="50%" /></p>
<p>이 10개의 자료를 X축을 학습시간, Y는 직무성과점수로 두고 산점도를 그려보자. 10개의 점이 찍혀 있는 그래프를 보면 학습시간이 많은 사람일수록 직무성과 점수가 대체로 높다는 것을 알 수 있다. 오른쪽 그래프에는 10개의 점을 가장 잘 설명하는 직선을 하나 그려보았다. 이 직선은 1차 함수(<span class="math inline">\(Y=10+3X\)</span>)로 간단히 표현할 수 있다.</p>
<p>1차 함수는 <span class="math inline">\(X\)</span>가 <span class="math inline">\(Y\)</span>에 대응되는 규칙이다. <span class="math inline">\(X\)</span>에 특정값을 투입하면 함수라는 규칙에 따라 특정한 <span class="math inline">\(Y\)</span>가 산출된다. 중학교 수학시간에 배웠던 간단한 1차 함수의 특징을 생각해보자</p>
<ul>
<li>절편(intercept) :<span class="math inline">\(X\)</span>가 0일때 <span class="math inline">\(Y\)</span>의 값</li>
<li>기울기(slope) :<span class="math inline">\(X\)</span>가 한 단위 변화할때 <span class="math inline">\(Y\)</span>가 변화하는 양이다.</li>
</ul>
<p>이 함수에서 절편은 10이다. 그래프에서도 <span class="math inline">\(X\)</span>가 0일때 <span class="math inline">\(Y\)</span>값은 10인것을 확인할 수 있다. 이 절편은 회귀분석시에도 자주 해석이 되므로 기억할 필요가 있다. 이 데이터에서는 <span class="math inline">\(X\)</span>(학습시간)이 0인 사람의 예측되는 <span class="math inline">\(Y\)</span>(직무성과점수)가 10점이라고 해석할 수 있다.
기울기는 <span class="math inline">\(X\)</span>로 미분한 값으로도 해석할수 있는데, 1차 함수이기 때문에 기울기는 “3”인 상수이다. 다시 말하면 어떠한 <span class="math inline">\(X\)</span>값이든 한 단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량이 동일하다는 것이다. 파란선의 기울기가 어떠한 구간에서도 동일한 직선임을 확인하자. 이러한 1차 함수의 특징을 고려하여 <span class="math inline">\(X\)</span>와 <span class="math inline">\(Y\)</span>가 선형적인 관계(Linear relationship)라고 부른다.</p>
</div>
<div id="기울기의-의미" class="section level3 hasAnchor" number="8.2.2">
<h3><span class="header-section-number">8.2.2</span> 기울기의 의미<a href="intuitive.html#%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>여기서 기울기는 보통 “회귀계수(regression coefficient)”라고 불린다. 독립변수(X)와 종속변수(Y)의 관계를 나타내는 계수이다. 회귀계수를 해석하는 방식은 1차 함수에서 기울기 값을 이해하면 매우 쉽게 기억할 수 있다.</p>
<ul>
<li>기울기(회귀계수)의 부호
<ul>
<li>양의 값(+)을 가지면 : X와 Y의 관계가 정적(positive)이다. X가 증가할때 Y가 증가한다.</li>
<li>음의 값(-)을 가지면 : X와 Y의 관계가 부적(negative)이다. X가 증가할 때 Y가 감소한다.</li>
</ul></li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-101-1.png" alt="" width="672" /></p>
</div>
<div id="haty-y와-잔차residual" class="section level3 hasAnchor" number="8.2.3">
<h3><span class="header-section-number">8.2.3</span> <span class="math inline">\(\hat{Y}\)</span>, <span class="math inline">\(Y\)</span>와 잔차(residual)<a href="intuitive.html#haty-y%EC%99%80-%EC%9E%94%EC%B0%A8residual" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>’학습시간(<span class="math inline">\(X\)</span>)과 ’직무성과(<span class="math inline">\(Y\)</span>)’의 그래프를 다시 살펴보자. <span class="math inline">\(Y=10+3X\)</span>라는 1차함수는 <span class="math inline">\(X\)</span>를 투입했을 때 산출되는 <span class="math inline">\(Y\)</span>의 값이다. 우리가 갖고 있는 10개의 데이터는 이 함수에 의해 대체로 잘 예측되고 있지만, 그렇지 않은 데이터도 있다.</p>
<ul>
<li>ID=1인 사람의 학습시간(<span class="math inline">\(X\)</span>)은 1이고, 직무성과(<span class="math inline">\(Y\)</span>)는 12이다. 함수에 의해 예측되는 <span class="math inline">\(Y\)</span>값은 <span class="math inline">\(10+(3*1)=13\)</span> 으로 “1만큼의 격차가 있다. 이때 함수에 의해 예측되는”13”을 우리는 <span class="math inline">\(\hat{Y}\)</span>라고 부른다.</li>
<li>이와 동일하게 나머지 데이터에서도 <span class="math inline">\(\hat{Y}\)</span>를 다음의 표와 같이 계산할 수 있다.</li>
<li>실제 관측된 <span class="math inline">\(Y\)</span>와 계산된 <span class="math inline">\(\hat{Y}\)</span>의 차이(difference)도 옆에 계산해보자. <span class="math inline">\(Y-\hat{Y}\)</span>= 잔차(residual)로 정의한다.</li>
</ul>
<table style="width:100%;">
<colgroup>
<col width="7%" />
<col width="23%" />
<col width="23%" />
<col width="30%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th align="center">ID</th>
<th align="center"><span class="math inline">\(X\)</span>(학습시간)</th>
<th align="center"><span class="math inline">\(Y\)</span>(직무성과)</th>
<th align="center">예측된 <span class="math inline">\(Y\)</span>(<span class="math inline">\(\hat{Y}\)</span>)</th>
<th align="center"><span class="math inline">\(Y\)</span>-<span class="math inline">\(\hat{Y}\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">12</td>
<td align="center">13</td>
<td align="center">-1.0</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0.5</td>
<td align="center">11</td>
<td align="center">11.5</td>
<td align="center">-0.5</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">18</td>
<td align="center">16</td>
<td align="center">2</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">3</td>
<td align="center">19</td>
<td align="center">19</td>
<td align="center">0.0</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">3</td>
<td align="center">21</td>
<td align="center">19</td>
<td align="center">2.0</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">3.5</td>
<td align="center">18.5</td>
<td align="center">20.5</td>
<td align="center">-2.0</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">4</td>
<td align="center">21.5</td>
<td align="center">22</td>
<td align="center">-0.5</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">4</td>
<td align="center">23.5</td>
<td align="center">22</td>
<td align="center">1.5</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">4.5</td>
<td align="center">22.5</td>
<td align="center">23.5</td>
<td align="center">-1.0</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">5</td>
<td align="center">25</td>
<td align="center">25</td>
<td align="center">0.0</td>
</tr>
</tbody>
</table>
<p>여기에 아랫첨자(<span class="math inline">\(i\)</span>)를 넣어서 종합해보면 다음과 같다.</p>
<ul>
<li><span class="math inline">\(X_i\)</span> : <span class="math inline">\(i\)</span>번째 사람의 관측된 <span class="math inline">\(X\)</span>값이다. 예: <span class="math inline">\(X_3\)</span><span class="math inline">\(=2\)</span></li>
<li><span class="math inline">\(Y_i\)</span> : <span class="math inline">\(i\)</span>번째 사람의 관측된(observed) <span class="math inline">\(Y\)</span>값이다. 예: <span class="math inline">\(Y_3\)</span><span class="math inline">\(=18\)</span>
이때 “관측되었다”는 뜻은 우리가 관찰한, 또는 측정한 값이라는 뜻이다. (가상의 값이 아님)</li>
<li><span class="math inline">\(\hat{Y}_i\)</span> : <span class="math inline">\(i\)</span>번째 사람의 예측된(predicted) <span class="math inline">\(Y\)</span>값이다. 예: <span class="math inline">\(\hat{Y}_3\)</span><span class="math inline">\(=16\)</span>. 예측된 값 16은 <span class="math inline">\(\hat{Y}=10+3X\)</span>라는 추정된 회귀식에 <span class="math inline">\(X_3=2\)</span>의 값을 넣어서 생성된 값이다(10+(3*2)=16)</li>
<li><span class="math inline">\(residual_i\)</span> = <span class="math inline">\(Y_i-\hat{Y}_i\)</span>. : <span class="math inline">\(i\)</span>번째 사람의 관측값과 예측된 값의 차이이다. 예: <span class="math inline">\(residual_3\)</span><span class="math inline">\(=2\)</span></li>
</ul>
<p>회귀식은 우리의 관측치를 완벽히 설명할수가 없기 때문에, 잔차는 필연적으로 발생한다. 예를 들어 ID 4번과 5번은 <span class="math inline">\(X\)</span>의 값이 3으로 같다. 10개의 데이터를 통해 추정된 회귀식 <span class="math inline">\(\hat{Y}=10+3X\)</span>에 <span class="math inline">\(X=3\)</span>을 투입하면 <span class="math inline">\(\hat{Y}\)</span>는 19이다. ID 4번의 사람은 <span class="math inline">\(Y\)</span>가 19로 <span class="math inline">\(\hat{Y}\)</span> 19와 같아잔차가 0인데 반해, ID 5번의 사람은 <span class="math inline">\(Y_4=21\)</span>로 잔차가 2만큼 발생한다.</p>
<p>잔차는 작을수록 좋다. 우리가 추정한 회귀식이 관측된 값들을 잘 예측한다는 뜻이기 때문이다. 따라서 회귀분석을 할때 추정되는 회귀계수(절편과 회귀)는 잔차를 최소화하는 방식으로 계산된다. 이와 관련한 자세한 내용은 Chapter 9에서 다루도록 하겠다.</p>
<p>위의 데이터를 활용해서 실제로 회귀분석을 실시해보자. Chapter 9에서 다루겠지만 R에서 회귀분석은 매우 간단한 코드로 이루어져있다. 여기서 산출되는 값을 활용해 다시 한번 회귀식을 제대로 이해해보자.</p>
<div class="sourceCode" id="cb93"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb93-1"><a href="intuitive.html#cb93-1" tabindex="-1"></a>ID<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>) </span>
<span id="cb93-2"><a href="intuitive.html#cb93-2" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">3.5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">5</span>)</span>
<span id="cb93-3"><a href="intuitive.html#cb93-3" tabindex="-1"></a>Y<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">11</span>, <span class="dv">18</span>, <span class="dv">19</span>, <span class="dv">21</span>, <span class="fl">18.5</span>, <span class="fl">21.5</span>, <span class="fl">23.5</span>, <span class="fl">22.5</span>, <span class="dv">25</span>)</span>
<span id="cb93-4"><a href="intuitive.html#cb93-4" tabindex="-1"></a>Learning <span class="ot">&lt;-</span><span class="fu">data.frame</span>(ID, X, Y)</span>
<span id="cb93-5"><a href="intuitive.html#cb93-5" tabindex="-1"></a>learningReg <span class="ot">&lt;-</span><span class="fu">lm</span>(Y <span class="sc">~</span> X, <span class="at">data=</span>Learning)</span>
<span id="cb93-6"><a href="intuitive.html#cb93-6" tabindex="-1"></a><span class="fu">summary</span>(learningReg)</span>
<span id="cb93-7"><a href="intuitive.html#cb93-7" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb93-8"><a href="intuitive.html#cb93-8" tabindex="-1"></a><span class="do">## Call:</span></span>
<span id="cb93-9"><a href="intuitive.html#cb93-9" tabindex="-1"></a><span class="do">## lm(formula = Y ~ X, data = Learning)</span></span>
<span id="cb93-10"><a href="intuitive.html#cb93-10" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb93-11"><a href="intuitive.html#cb93-11" tabindex="-1"></a><span class="do">## Residuals:</span></span>
<span id="cb93-12"><a href="intuitive.html#cb93-12" tabindex="-1"></a><span class="do">##     Min      1Q  Median      3Q     Max </span></span>
<span id="cb93-13"><a href="intuitive.html#cb93-13" tabindex="-1"></a><span class="do">## -2.0437 -0.9187 -0.2937  1.0917  1.9493 </span></span>
<span id="cb93-14"><a href="intuitive.html#cb93-14" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb93-15"><a href="intuitive.html#cb93-15" tabindex="-1"></a><span class="do">## Coefficients:</span></span>
<span id="cb93-16"><a href="intuitive.html#cb93-16" tabindex="-1"></a><span class="do">##             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb93-17"><a href="intuitive.html#cb93-17" tabindex="-1"></a><span class="do">## (Intercept)  10.0925     1.0930   9.233 1.53e-05 ***</span></span>
<span id="cb93-18"><a href="intuitive.html#cb93-18" tabindex="-1"></a><span class="do">## X             2.9861     0.3255   9.173 1.61e-05 ***</span></span>
<span id="cb93-19"><a href="intuitive.html#cb93-19" tabindex="-1"></a><span class="do">## ---</span></span>
<span id="cb93-20"><a href="intuitive.html#cb93-20" tabindex="-1"></a><span class="do">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb93-21"><a href="intuitive.html#cb93-21" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb93-22"><a href="intuitive.html#cb93-22" tabindex="-1"></a><span class="do">## Residual standard error: 1.446 on 8 degrees of freedom</span></span>
<span id="cb93-23"><a href="intuitive.html#cb93-23" tabindex="-1"></a><span class="do">## Multiple R-squared:  0.9132, Adjusted R-squared:  0.9023 </span></span>
<span id="cb93-24"><a href="intuitive.html#cb93-24" tabindex="-1"></a><span class="do">## F-statistic: 84.15 on 1 and 8 DF,  p-value: 1.611e-05</span></span>
<span id="cb93-25"><a href="intuitive.html#cb93-25" tabindex="-1"></a><span class="fu">resid</span>(learningReg)</span>
<span id="cb93-26"><a href="intuitive.html#cb93-26" tabindex="-1"></a><span class="do">##           1           2           3           4           5           6 </span></span>
<span id="cb93-27"><a href="intuitive.html#cb93-27" tabindex="-1"></a><span class="do">## -1.07858048 -0.58555133  1.93536122 -0.05069708  1.94930292 -2.04372624 </span></span>
<span id="cb93-28"><a href="intuitive.html#cb93-28" tabindex="-1"></a><span class="do">##           7           8           9          10 </span></span>
<span id="cb93-29"><a href="intuitive.html#cb93-29" tabindex="-1"></a><span class="do">## -0.53675539  1.46324461 -1.02978454 -0.02281369</span></span></code></pre></div>
<p>R의 내장함수인 <code>lm</code>을 사용하면 간단히 회귀분석을 실시할 수 있다. 명령어의 사용법은 다음과 같다.
* 회귀분석결과 &lt;- lm(종속변수 ~ 독립변수, data=사용할 data.frame)
또한 회귀분석결과와 잔차를 확인하는 명령어는 다음과 같다.
* summary(회귀분석결과)
* reisid (회귀분석결과)</p>
<p>산출된 회귀분석결과를 살펴보면 크게 두 가지의 coeffocient가 추정되어 있다. <code>절편</code>(Intercept)과 <code>기울기</code>(X)이다. 절편의 추정지는 10.0925, 기울기의 추정치는 2.9861이다. 추정치 옆에는 3개의 값이 붙는다 표준오차(standard error)와 t-value, 그리고 p-value이다. 이 3개의 값의 의미는 chapter 9에서 다시 다룰테니 일단 넘어가자.
절편과 기울기의 추정치를 활용하여 회귀식을 구성하보면 다음과 같다. <a href="intuitive.html#eq:reglearning1">(8.1)</a></p>
<p><span class="math display" id="eq:reglearning1">\[\begin{equation}
\hat{Y} = 10.0925+(2.9861*X)
\tag{8.1}
\end{equation}\]</span></p>
<p><a href="intuitive.html#eq:reglearning1">(8.1)</a>를 잔차가 포함된 회귀식으로 다시 쓰면 <a href="intuitive.html#eq:reglearning2">(8.2)</a>과 같다.
<span class="math display" id="eq:reglearning2">\[\begin{equation}
Y = 10.0925+(2.9861*X) + e
\tag{8.2}
\end{equation}\]</span></p>
<p><code>resid()</code>를 활용해서 호출한 10개의 잔차값을 확인하면 -2.0437부터 1.9493 까지 분포를 보인다. 이 중 첫번째 사람(ID=1)의 데이터를 활용해서 회귀식을 재확인해보자.</p>
<ul>
<li><span class="math inline">\(X_1=1\)</span>, <span class="math inline">\(residual_1=-1.0785048\)</span>이고,</li>
<li><span class="math inline">\(Y = 10.0925+(2.9861*X) + e\)</span>에 위의 값을 넣어보면,</li>
<li>10.0925+(2.9861*1)-1.0785048 =12.0001로 <span class="math inline">\(Y_1=12\)</span>과 같은 것을 확인할 수 있다.</li>
</ul>
<p>많은 사람들이 회귀분석결과를 해석할때 다음과 같은 오류를 범한다.</p>
<ul>
<li>절편을 해석하지 않거나,</li>
<li>회귀계수의 유의성에만 의미를 부여하거나, (p&lt;0.001 수준에서 유의했다)</li>
<li>회귀계수의 부호만 해석한다 (정적인 효과가 있다, 부적인 효과가 있다)</li>
</ul>
<p>이를 방지하기 위해서는 반드시 회귀식을 만들어서, 좀 더 선명한 해석을 할 필요가 있다. 회귀식을 만들어 절편과 기울기의 의미를 정확히 이해하고 해석한다면 보다 풍부한 설명이 가능하다. 또한 이러한 단순회귀식을 정확히 이해해야만, 조절효과, 매개효과, 구조방정식, 다층모형 등 다양한 고급 다변량 분석을 손쉽게 이해할 수 있다.</p>
</div>
<div id="독립변수가-두-개-이상일때의-회귀식" class="section level3 hasAnchor" number="8.2.4">
<h3><span class="header-section-number">8.2.4</span> 독립변수가 두 개 이상일때의 회귀식<a href="intuitive.html#%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EA%B0%80-%EB%91%90-%EA%B0%9C-%EC%9D%B4%EC%83%81%EC%9D%BC%EB%95%8C%EC%9D%98-%ED%9A%8C%EA%B7%80%EC%8B%9D" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>지금까지 살펴본 회귀식은 독립변수가 1개인 <code>단순회귀분석</code>이다. 따라서 X와 Y의 관계를 간단한 1차함수로 설명할 수 있다. 산업인력개발 연구장면에서는 대부분 독립변수 X가 2개 이상인 <code>다중회귀분석(multi-variate regression)</code>을 수행한다.
회귀분석의 목적은 종속변수(Y)를 예측하는 것이라는 점을 생각해보면, 종속변수를 설명하는 독립변수는 많은 것이 자연스럽다. 앞서 다뤘던 재직자의 직무성과 점수를 예측하는 첫번째 독립변수(<span class="math inline">\(X1\)</span>, 학습시간)을 생각해보자. 개인의 직무성과에 미치는 영향을 미치는 다른 변수(<span class="math inline">\(X2\)</span>, 근무기간)이 있다고 가정할 수 있다. 이 데이터를 다음과 같이 확보했다고 생각해보자.</p>
<table>
<thead>
<tr class="header">
<th align="center">ID</th>
<th align="center">X1(학습시간)</th>
<th align="center">X2(근무기간)</th>
<th align="center">Y(직무성과)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">16</td>
<td align="center">12</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">0.5</td>
<td align="center">20</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">2</td>
<td align="center">28</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">3</td>
<td align="center">29</td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">3</td>
<td align="center">32</td>
<td align="center">21</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">3.5</td>
<td align="center">30</td>
<td align="center">18.5</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">4</td>
<td align="center">50</td>
<td align="center">21.5</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">4</td>
<td align="center">41</td>
<td align="center">23.5</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">4.5</td>
<td align="center">40</td>
<td align="center">22.5</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">5</td>
<td align="center">60</td>
<td align="center">25</td>
</tr>
</tbody>
</table>
<p>종속변수 1개와 독립변수 1개의 관계는 2차원으로 표현할 수 있었다. 당연하게도 종속변수 2개와 독립변수 1개의 관계는 3차원으로 표현해야 한다. 아래 그림은 종속변수 <span class="math inline">\(Y\)</span>를 Z축으로 두고 10개의 데이터를 좌표에 표시한 것이다. 데이터는 3개의 좌표를 갖기 때문에 데이터의 집합은 더이상 <code>선</code>이 아니라 <code>면</code>의 형태를 갖게 된다. 두 번째 그림은 데이터를 가장 잘 설명하는, 다시 말해 잔차를 최소화하는 평평한 면을 표시한 것이다.</p>
<pre><code>## Error in `library()`:
## ! there is no package called &#39;plot3D&#39;
## Error in `scatter3D()`:
## ! could not find function &quot;scatter3D&quot;
## Error in `scatter3D()`:
## ! could not find function &quot;scatter3D&quot;</code></pre>
<p>이처럼 독립변수가 2개 이상이 되면 더이상 1차 함수로 설명하기 곤란해진다. 독립변수가 2개이면 3차원으로 표시가 가능하하지만, 독립변수가 3개라면 4차원, 4개라면 5차원 등 시각화가 어려워지기 때문에 더욱 어렵다. 따라서 다중회귀분석부터는 회귀식으로 이해하는 것이 편리하다.
위의 그래프에서 활용한 두 개의 독립변수(<span class="math inline">\(X1\)</span>, <span class="math inline">\(X2\)</span>)를 <span class="math inline">\(Y\)</span>에 대해 회귀분석을 해보자. 아래 결과표를 활용해서 회귀식을 구성해보면 아래와 같다.</p>
<pre><code>## 
## Call:
## lm(formula = Y ~ X1 + X2, data = multiLearning)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -1.6684 -0.8821 -0.6049  1.1867  2.0497 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)  9.63316    1.41213   6.822 0.000248 ***
## X1           2.61870    0.74485   3.516 0.009784 ** 
## X2           0.04566    0.08233   0.555 0.596458    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 1.513 on 7 degrees of freedom
## Multiple R-squared:  0.9168, Adjusted R-squared:  0.8931 
## F-statistic: 38.59 on 2 and 7 DF,  p-value: 0.0001659
##          1          2          3          4          5          6          7 
## -0.9824018 -0.8556850  1.8509879  0.1866247  2.0496482 -1.6683863 -0.8909152 
##          8          9         10 
##  1.5200143 -0.7436790 -0.4662078</code></pre>
<p><span class="math display">\[\small Y=9.63316+2.61870*(X1)+0.04566(X2)+e\]</span></p>
<p>우리는 총 3개의 추정치(절편, X1의 기울기, X2의 기울기)를 갖는다.</p>
<ul>
<li><p>절편 :<span class="math inline">\(X1\)</span>과 <span class="math inline">\(X2\)</span>가 모두 0일때, <span class="math inline">\(Y\)</span>의 값
<span class="math inline">\(\small 9.63316=9.63316+2.618720*0 + 0.04566*0\)</span></p></li>
<li><p>X1의 기울기(회귀계수) : 회귀식을 <span class="math inline">\(X1\)</span>으로 편미분한 값. 해석은 다음과 같이 다양함
** X2를 상수(constant)로 두었을 때, <span class="math inline">\(X1\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X2를 고정했을 때, <span class="math inline">\(X1\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X2를 통제했을 때, <span class="math inline">\(X1\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X2가 random하게 assigned되었을때, <span class="math inline">\(X1\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량</p></li>
<li><p>X2의 기울기(회귀계수) : 회귀식을 <span class="math inline">\(X2\)</span>으로 편미분한 값.
** X1를 상수(constant)로 두었을 때, <span class="math inline">\(X2\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X1를 고정했을 때, <span class="math inline">\(X2\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X1를 통제했을 때, <span class="math inline">\(X2\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량
** X1이 random하게 assigned되었을때, <span class="math inline">\(X2\)</span> 한단위 변화할때 <span class="math inline">\(Y\)</span>의 변화량</p></li>
</ul>
<p>이제 회귀식이 눈에 익을것이라고 생각한다. 이상의 내용을 종합해서 기본적인 선형 회귀식은 <a href="intuitive.html#eq:basicreg">(8.3)</a>과 같이 쓸 수 있다.</p>
<p><span class="math display" id="eq:basicreg">\[\begin{equation}
Y = \beta_{0}+\beta_{1}*X_{1}+\beta_{2}*X_{2}+\cdots+\beta_{i}*X_{i}+ e
\tag{8.3}
\end{equation}\]</span></p>
</div>
<div id="added-variable-plot" class="section level3 hasAnchor" number="8.2.5">
<h3><span class="header-section-number">8.2.5</span> added variable plot<a href="intuitive.html#added-variable-plot" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>많은 사람들이다중회귀분석을 해석할때 통제 변수에 대한 해석을 어려워한다. 좀더 간편한 이해를 위해 예를 들어 설명해보려고 한다.</p>
<p>만일 독립변수가 두 개인 경우라면, <a href="intuitive.html#eq:basicreg2">(8.4)</a>와 같이 쓸 수 있다.
<span class="math display" id="eq:basicreg2">\[\begin{equation}
Y = \beta_{0}+\beta_{1}*X_{1}+\beta_{2}*X_{2}+ e
\tag{8.4}
\end{equation}\]</span></p>
<p>또한 이때 독립변수 두개는 정적인 상관관계를 가진다고 가정하자(대부분의 사회과학의 변수가 상관관계가 있다는 걸 염두에 두자). 또한 <span class="math inline">\(X_{1}\)</span>과 <span class="math inline">\(Y\)</span>, <span class="math inline">\(X_{2}\)</span>와 <span class="math inline">\(Y\)</span>는 모두 정적인 관계를 갖는다고 가정한다. 이때 <span class="math inline">\(\beta_{1}\)</span>와 <span class="math inline">\(\beta_{2}\)</span>를 어떻게 해석해야 할까? 먼저 <span class="math inline">\(\beta_{1}\)</span>을 해석해보자.</p>
<p><a href="intuitive.html#eq:basicreg2">(8.4)</a>에서 <span class="math inline">\(\beta_{1}\)</span>는 <span class="math inline">\(X_{2}\)</span>를 고정했을때(또는 통제했을때의, <span class="math inline">\(X_{1}\)</span>이 Y에 미치는 영향이다.
반대로 오직 <span class="math inline">\(X_{1}\)</span>만 투입한 단순회귀분석을 생각해보면 다음과 같다.
<span class="math inline">\(Y = {\beta_{0}}&#39;+{\beta_{1}}&#39;*X_{1}+{e}&#39;\)</span>
당연히 절편, 기울기, 잔차 모두 <a href="intuitive.html#eq:basicreg2">(8.4)</a>와 달라진다. 이때 <span class="math inline">\({\beta_{1}}&#39;\)</span>는 <span class="math inline">\(X_{2}\)</span>를 고정하지 않았을 때의 회귀식이다.
만일 <span class="math inline">\(X_{2}\)</span>와 <span class="math inline">\(Y\)</span>가 정적인 영향관계가 있다면 <span class="math inline">\(\beta_{1}&gt;0\)</span>이다. 하지만 <span class="math inline">\(X_{1}\)</span>이 증가할수록 <span class="math inline">\(X_{2}\)</span>가 함게 증가하고(두 변수가 positively correlated), <span class="math inline">\(\beta_{2}&gt;0\)</span>이므로, <span class="math inline">\(Y\)</span>의 평균값은 <span class="math inline">\(X_{1}\)</span>만 단독 투입했을 때보다 증가한다. 따라서 <span class="math inline">\(\beta_{1}&lt;\ {\beta_{1}}&#39;\)</span>이 된다. 만일 <span class="math inline">\(X_{1}\)</span>과 <span class="math inline">\(X_{2}\)</span>의 상관관계가 강하다면, 이러한 경향성은 더욱 강화된다.</p>
<p>따라서 하나의 독립변수와 종속변수의 simple regression graph를 그려 설명하는 것은 매우 위험하다. 대신에 나머지 변수들을 통제하고 관심변수와 종속변수의 관계를 설명할 수 있는 그래프인 ‘added variable plot’, ’partial regression plot’을 활용하는 것이 좋다. Frisch-Waugh-Lovell theorem을 활용하여 다른 독립변수의 영향력을 ’partial out’시킨 결과를 그래프에 표시하는 것이다.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-105-1.png" alt="" width="672" /></p>
<p>위의 value added 그래프의 좌측은 X1-Y의 관계, 우측은 X2-Y의 관계를 의미한다. 좌측을 중심으로 설명하면 Y축은 ‘Y &lt;- X2’ 회귀식의 잔차를 나타내고 있다. X축은 ’X1 &lt;- X2’회귀식의 잔차를 나타낸다. 종속변수와 독립변수 모두 X2가 미치는 영향을 partial out 한 것이다.</p>
</div>
</div>
<div id="회귀분석과-2차함수" class="section level2 hasAnchor" number="8.3">
<h2><span class="header-section-number">8.3</span> 회귀분석과 2차함수<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EA%B3%BC-2%EC%B0%A8%ED%95%A8%EC%88%98" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="비선형-회귀분석" class="section level3 hasAnchor" number="8.3.1">
<h3><span class="header-section-number">8.3.1</span> 비선형 회귀분석<a href="intuitive.html#%EB%B9%84%EC%84%A0%ED%98%95-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>지금까지 우리가 다른 회귀분석은 선형적(linear)이었다. 이때 선형이라는 뜻은 X값에 관계없이 X-Y의 관계가 일정하다, 다시 말해 기울기값이 동일하다는 뜻이다. <span class="math inline">\(Y=a+bx\)</span>의 간단한 1차함수를 떠올려보면, X와 Y의 관계는 언제나 일정하다.</p>
<p>비선형관계의 회귀분석은 보통 2차 함수부터 시작한다. 중학교때 배웠던 2차 함수의 포물선을 생각해보자. 가장 기본적인 형태의 2차함수는 다음과 같이 표현한다. <span class="math inline">\(Y=aX^2+bX+c\)</span>.</p>
<p>아래 그래프는 <span class="math inline">\(Y=X^2+2X-24\)</span>를 그래프로 표현한 것이다. 그래프를 그리기 위해 중요한 값 3개가 있다.</p>
<ul>
<li>‘X 절편’ = <span class="math inline">\(Y\)</span>=0의 값을 갖는 <span class="math inline">\(X\)</span>값
예: <span class="math inline">\(0=X^2+2X-24=(X+4)(X-6)\)</span>이므로 ’-4’와 ’6’이다.</li>
<li>‘Y 절편’ = <span class="math inline">\(X\)</span>=0의 값을 갖는 <span class="math inline">\(Y\)</span>값
<span class="math inline">\(y= a*0^2+b*0+c\)</span> 이므로 ’c=-24’이다.</li>
<li>꼭지점 :Y가 최대(a&lt;0) 또는 최소(a&gt;0)의 값을 갖는 지점
<span class="math inline">\(X=-\frac{b}{2a}\)</span>,<span class="math inline">\(Y=f(-\frac{b}{2a})\)</span>
따라서 (-1, -25)이다.</li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-106-1.png" alt="" width="672" /></p>
<p>2차함수의 모양은 a, b, c의 값에 따라 달라진다. 아래 그래프를 보면 각 계수의 부호에 따라 그래프의 모양과 위치가 달라지는 것을 알 수 있다. 중학교 시절 수학을 떠올려보면 다음과 같이 정리가 가능하다.</p>
<ul>
<li><p>2차항의 계수 ’a’의 부호 : 그래프의 오목함과 볼록함을 결정</p>
<ul>
<li>a&gt;0 : 볼록한 비선형</li>
<li>a&lt;0 : 오목한 비선형</li>
</ul></li>
<li><p>1차항의 계수 ’b’의 부호 : y축을 지날때 상승/하강</p>
<ul>
<li>b&gt;0 : 좌에서 우로 y축을 지날때 상승</li>
<li>b&lt;0 : 좌에서 우로 y축을 지날때 하강</li>
</ul></li>
<li><p>상수항의 계수 ’c’의 부호 : 그래프의 <span class="math inline">\(Y\)</span>절편을 결정함</p>
<ul>
<li>c&gt;0 : y 절편이 양의 값</li>
<li>c&lt;0 : y 절편이 음의 값</li>
</ul></li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-107-1.png" alt="" width="672" /></p>
<p><img src="_main_files/figure-html/unnamed-chunk-108-1.png" alt="" width="672" /></p>
<p>예를 들어 개인의 시험점수(Y)와 학습시간(X)의 관계를 2차 함수로 설명해보자. 첫번째 그래프의 함수인 <span class="math inline">\(Y=2X+20X+100\)</span>를 회귀식으로 쓰면<a href="intuitive.html#eq:regnonlinear">(8.5)</a>와 같다.</p>
<p><span class="math display" id="eq:regnonlinear">\[\begin{equation}
\hat{Y} = 100+(20*X)+2X^2
\tag{8.5}
\end{equation}\]</span></p>
</div>
<div id="절편의-의미" class="section level3 hasAnchor" number="8.3.2">
<h3><span class="header-section-number">8.3.2</span> 절편의 의미<a href="intuitive.html#%EC%A0%88%ED%8E%B8%EC%9D%98-%EC%9D%98%EB%AF%B8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>여기서 Y 절편은 100으로, ’X가 0일때 Y의 값’이다. 그래프에서 포물선이 Y축을 지날때 Y값이 100인것을 확인하자. 이 연구문제에서는 학습시간이 0인 사람의 예측된 시험점수(predicted Y, <span class="math inline">\(\hat{y}\)</span>)가 100점이라는 뜻이다.</p>
</div>
<div id="차항및-2차항의-기울기의-의미" class="section level3 hasAnchor" number="8.3.3">
<h3><span class="header-section-number">8.3.3</span> 1차항및 2차항의 기울기의 의미<a href="intuitive.html#%EC%B0%A8%ED%95%AD%EB%B0%8F-2%EC%B0%A8%ED%95%AD%EC%9D%98-%EA%B8%B0%EC%9A%B8%EA%B8%B0%EC%9D%98-%EC%9D%98%EB%AF%B8" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>선형 회귀분석(1차함수)와 달리 비선형 회귀분석에서는 기울기를 나타내는 항이 2개 이상으로 늘어난다. 2차함수를 기준으로 살펴보면, 기울기를 나타내는 항은 <span class="math inline">\(20X\)</span>와 <span class="math inline">\(2X^2\)</span>의 두개의 계수 값을 모두 해석해야 한다.</p>
<p>가장 간단하게 기울기를 확인할 수 있는 방법은 미분(differentiation)을 하는 것이다. 미분이란 어떤 면을 미세하게 층층히 쪼개었을때, 각각의 층을 ’미세한 부분’이라고 하여 미분이라고 부르는 것이 어원이다. 좀더 간단히 설명하면 ’한 점에서의 기울기’라고 할 수 있다.
<span class="math inline">\(Y=F(x)\)</span>라는 함수 위의 (a, f(a))라는 특정한 점에서의 기울기이고 <span class="math inline">\({f}&#39;(a)\)</span>로 표시한다. 이때 <span class="math inline">\({f}&#39;(a)\)</span> 는 다음과 같은 뜻이다.</p>
<ul>
<li>X=a 인 점에서의 기울기</li>
<li>X=a 인 점에서의 접선의 기울기</li>
<li>X=a 인 점에서의 미분값</li>
<li>X=a 인 점에서의 미분계수</li>
</ul>
<p>다시 원래의 회귀식<a href="intuitive.html#eq:regnonlinear">(8.5)</a>로 돌아와 생각해보자. 이 함수의 기울기(<span class="math inline">\(X\)</span>한단위 변화시 <span class="math inline">\(Y\)</span>의 변화량)을 구하기 위해서는 <span class="math inline">\(X\)</span>로 미분한다.
고등학교때 배웠던 간단한 미분공식을 활용해보면 아래와 같다. <a href="#fn5" class="footnote-ref" id="fnref5"><sup>5</sup></a>.</p>
<p><span class="math inline">\(\frac{d}{dx}f(x)={f}&#39;(x) = 2*2*X +20 = 4X+20\)</span></p>
<p>따라서 이 2차함수의 기울기는 4X+20이다. 2차항이 존재하기 때문에 <span class="math inline">\(X\)</span>로 한번 미분했을 때 상수가 아닌 X가 포함된 값이 나온다. 이것은 무엇을 의미할까? 이는 <span class="math inline">\(X\)</span>의 값에 따라 기울기의 값이 변화한다는 비선형함수의 특징을 나타낸다.
잘 이해가 안될때는 X에 특정 값을 반복해서 넣고, 이를 그래프로 이해해보자.
<img src="images/differ.png" alt="2차항이 있는 회귀분석의 기울기" /></p>
<ul>
<li><p>X=0일때, 기울기= <span class="math inline">\(4*0+20 = 20\)</span></p></li>
<li><p>X=1일때, 기울기= <span class="math inline">\(4*1+20 = 24\)</span></p></li>
<li><p>X=2일때, 기울기= <span class="math inline">\(4*2+20 = 26\)</span></p></li>
<li><p>X=3일때, 기울기= <span class="math inline">\(4*3+20 = 28\)</span></p></li>
</ul>
<p>그림과 대입값에서 볼수 있듯이 기울기는 고정(constant)되지 않고, 계속 변화한다. 구체적으로는 <span class="math inline">\(X\)</span>가 증가할 수록 기울기는 점차 증가한다.</p>
<p>여기서 ‘기울기는 변화한다’는 뜻은 기울기의 ’변화량’이 존재한다는 뜻이다. 이때 기울기의 변화량은’ <span class="math inline">\(X\)</span>가 한단위 증가할때, <span class="math inline">\(Y\)</span>의 변화량의 변화량’이다. 이는 <span class="math inline">\(f(x)\)</span>를 <span class="math inline">\(X\)</span>로 두 번 미분한 값, 다시 말해 <span class="math inline">\({f}&#39;&#39;(x)\)</span>이다. 종합해보면 다음과 같다.</p>
<p><span class="math inline">\(\frac{d}{dx}{f}&#39;(x)\)</span>=<span class="math inline">\({f}&#39;&#39;(x)\)</span> = <span class="math inline">\(4\)</span></p>
<p>이 2차 함수를 두번 미분한 값, 다시 말해 기울기의 변화량은 ’4’이다. 위의 그림에서 X가 0일때 기울기가 20, X가 1일때 기울기가 24, X가 2일때 기울기가 28로, x가 한단위 변화할때 기울기는 ’4’씩 변화하는 것을 볼 수 있다.</p>
</div>
<div id="임금방정식으로-이해하는-비선형-회귀분석" class="section level3 hasAnchor" number="8.3.4">
<h3><span class="header-section-number">8.3.4</span> 임금방정식으로 이해하는 비선형 회귀분석<a href="intuitive.html#%EC%9E%84%EA%B8%88%EB%B0%A9%EC%A0%95%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EB%B9%84%EC%84%A0%ED%98%95-%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>비선형 회귀분석은 사회과학에서 빈번하게 활용된다. 가장 대표적인 사례는 Mincer (19##)의 임금 방정식일 것이다. 개인의 임금은 보통 연령에 따라 증가하지만 선형적인 관계는 아니다. 다시 말해 나이가들수록 임금이 상승하지만 기울기는 변화하다가, 특정한 나이에 정점을 찍고 살짝 감소하는 비선형 관계를 갖고 있다. Mincer의 임금방정식은 연령-임금의 관계를 기초로 교육연한, 경력연한 등의 관계를 구명하는 목적을 갖고 있지만, 우리는 단순화하여 연령-임금의 관계만 국한해서 설명해보자.</p>
<p><img src="_main_files/figure-html/unnamed-chunk-109-1.png" alt="" width="672" /></p>
<p>좌측의 그림은 1차함수(<span class="math inline">\(\small Y(임금)=5*X+100\)</span>), 우측의 그림은 2차함수 (<span class="math inline">\(\small Y(임금)=-0.04*X^2+5*X+200\)</span>)을 나타낸다. 선형관계인 1차함수는 나이가 증가할 수록 일정한 비율로 임금이 증가한다. 결국 20세에 200만원이었던 임금은 30세에 250만원, 40세에 300만원씩 올라가서 80세에는 500만원까지 끊임없이 증가하는 비현실적인 모습을 보인다. 실제 노동시장에서의 개인의 임금은 우측의 그림과 가깝다. 연령이 증가할수록 임금은 증가하긴 하지만 증가율은 점차 감소하는 것이다.</p>
<div id="선형-관계인-1차함수의-계수-해석" class="section level4 hasAnchor" number="8.3.4.1">
<h4><span class="header-section-number">8.3.4.1</span> 선형 관계인 1차함수의 계수 해석<a href="intuitive.html#%EC%84%A0%ED%98%95-%EA%B4%80%EA%B3%84%EC%9D%B8-1%EC%B0%A8%ED%95%A8%EC%88%98%EC%9D%98-%EA%B3%84%EC%88%98-%ED%95%B4%EC%84%9D" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li>회귀식 : <span class="math display">\[\small Y(임금)=5*X(연령)+100\]</span></li>
<li>X 절편 : 100
<ul>
<li>연령(X)가 0일때, Y(임금)의 값은 100만원이다.</li>
</ul></li>
<li>기울기 : <span class="math display">\[\small \frac{d}{dx}{f}(x)=5\]</span><br />
</li>
<li>애매한 해석:
<ul>
<li>임금과 연령은 정적인 관계가 있다.</li>
<li>연령이 증가할 수록 임금이 상승한다.</li>
</ul></li>
<li>선명한 해석:
<ul>
<li>연령(X)이 1살 증가하면, Y(임금)은 5만원씩 증가한다.</li>
<li>이밖에도 특정 연령의 예측 임금도 해석할 수 있다. 예) 40세일때 임금은 <span class="math inline">\(\small 5*40 +100=300\)</span>만원이다.</li>
</ul></li>
</ul>
</div>
<div id="비선형-관계인-2차-함수의-계수-해석" class="section level4 hasAnchor" number="8.3.4.2">
<h4><span class="header-section-number">8.3.4.2</span> 비선형 관계인 2차 함수의 계수 해석<a href="intuitive.html#%EB%B9%84%EC%84%A0%ED%98%95-%EA%B4%80%EA%B3%84%EC%9D%B8-2%EC%B0%A8-%ED%95%A8%EC%88%98%EC%9D%98-%EA%B3%84%EC%88%98-%ED%95%B4%EC%84%9D" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<ul>
<li><p>회귀식: <span class="math display">\[\small Y(임금)=-0.04*X^2+5*X+200\]</span></p></li>
<li><p>X 절편 : 100</p>
<ul>
<li>연령(X)가 0일때, Y(임금)의 값은 200만원이다.</li>
</ul></li>
<li><p>기울기 : <span class="math display">\[\small \frac{d}{dx}{f}(x)=-0.04*2*X+5= -0.08X+5\]</span></p></li>
<li><p>기울기의 변화량 : <span class="math display">\[\small \frac{d}{dx}{f}&#39;(x)= {f}&#39;&#39;(x) =-0.08\]</span></p></li>
<li><p>애매한 해석:</p>
<ul>
<li>연령과 임금의 관계는 정적이다(x의 계수가 양의 값이므로), 그러나 이 기울기는 점점 감소한다 (<span class="math inline">\(X^2\)</span>의 계수가 음의 값이므로)</li>
</ul></li>
<li><p>선명한 해석 :</p>
<ul>
<li>연령이 0세일때, 연령과 임금의 기울기는 5이다.</li>
<li>이 기울기는 10세에 <span class="math inline">\(\small 4.2=-0.08*10+5\)</span>, 20세에 <span class="math inline">\(\small 3.4=-0.08*20+5\)</span>로 양의 값을 갖지만, 그 크기가 점차 줄어든다.</li>
<li>연령과 임금의 기울기는 62.5세(-0.08*62.5+5=0)에 0의 값을 갖는다. 다시 말해 62.5세에 임금은 최고값을 갖는다.</li>
<li>기울기는 62.5세 이후에 0.08씩 하락해서 음의 값을 갖는다. 예를 들어 70세에는 -0.6(-0.08*70+5)의 값을 갖는다.</li>
</ul></li>
</ul>
</div>
</div>
</div>
<div id="회귀분석에서-더미변수-활용" class="section level2 hasAnchor" number="8.4">
<h2><span class="header-section-number">8.4</span> 회귀분석에서 더미변수 활용<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%97%90%EC%84%9C-%EB%8D%94%EB%AF%B8%EB%B3%80%EC%88%98-%ED%99%9C%EC%9A%A9" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="회귀분석에-적합한-변수의-척도" class="section level3 hasAnchor" number="8.4.1">
<h3><span class="header-section-number">8.4.1</span> 회귀분석에 적합한 변수의 척도<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EB%B6%84%EC%84%9D%EC%97%90-%EC%A0%81%ED%95%A9%ED%95%9C-%EB%B3%80%EC%88%98%EC%9D%98-%EC%B2%99%EB%8F%84" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>초보연구자들이 자주 하는 실수 중에 하나는 회귀분석에 적합하지 않은 변수를 연구에 사용하는 것이다. 1장에서 다뤘던 것처럼 우리가 통상 사용하는 변수의 척도(scale)는 크게 네가지 이다.</p>
<ul>
<li><code>명목척도</code> (categorical scale) : 숫자로 표현할 수 없다. 예) 색깔 (빨간색, 파란색, 노란색 등), 성별(남자, 여자), 통학방식(도보, 자가용, 대중교통 등)</li>
<li><code>서열척도</code> (ordinal scale) : 숫자로 표현할 수 있고, 방향이 있다 (크고, 작고). 그러나 숫자간의 간격이 동간이 아니기때문에 덧셈, 뺄셈을 할 수 없다. 예) 올림픽성적(1등, 2등, 3등), 총선투표결과 (1등, 2등, 3등)</li>
<li><code>등간 척도</code>(interval scale): 숫자로 표현할 수 있고, 방향이 있으며, 숫자간의 간격이 동간이다. 따라서 덧셈, 뺄셈을 할 수 있다. 예) 리커트 척도로 측정된 자기보고점수, 시험성적 등</li>
<li><code>비율척도</code>(ratio scale): 숫자로 표현할 수 있고, 방향이 있으며, 숫자간의 간격도 동간이다. 또한 절대 0점을 포함한다. 예) 몸무게, 키 등</li>
</ul>
<p>변수의 척도가 서열척도라면 회귀분석에 포함될 수 없다. 앞서 살펴본 1차 함수가 회귀식의 원형이라는 점을 기억해보면 너무나 당연할 것이다. 독립변수(X)가 명목척도인 다음의 예를 생각해보자. 혈액형은 A형=1, B형=2, O형=3으로 코딩하였다.</p>
<table>
<thead>
<tr class="header">
<th align="center">ID</th>
<th align="center">X(혈액형)</th>
<th align="center">Y(직무성과)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">12</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">1</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">1</td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">2</td>
<td align="center">21</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">2</td>
<td align="center">18.5</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">2</td>
<td align="center">21.5</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">2</td>
<td align="center">23.5</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">3</td>
<td align="center">22.5</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">3</td>
<td align="center">25</td>
</tr>
</tbody>
</table>
<pre><code>## 
## Call:
## lm(formula = Y ~ X, data = bloodLearning)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -4.5000 -2.0938  0.5625  2.2188  3.5000 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)   10.875      2.485   4.376  0.00236 **
## X              4.625      1.275   3.628  0.00671 **
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.017 on 8 degrees of freedom
## Multiple R-squared:  0.6219, Adjusted R-squared:  0.5747 
## F-statistic: 13.16 on 1 and 8 DF,  p-value: 0.006706
##      1      2      3      4      5      6      7      8      9     10 
## -3.500 -4.500  2.500  3.500  0.875 -1.625  1.375  3.375 -2.250  0.250</code></pre>
<p>위의 분석결과처럼 혈액형과 같은 명목척도를 투입하더라도, 1, 2, 3과 같이 숫자로 코딩되어 있기 때문에 결과는 도출된다. 통계패키지는 이 변수가 명목척도라는 것을 알수 없다. 따라서 그럴듯해보이지만 엉터리 분석결과가 산출되었다. 위의 결과표를 이용해 회귀식을 만들어보자.</p>
<ul>
<li><span class="math inline">\(Y=10.875+4.625*X(혈액형)+e\)</span></li>
</ul>
<p>회귀식을 만들지 않는다면, 결과표를 보고 “혈액형이 직무성과에 정적인 영향을 미친다” 같은 엉뚱한 분석을 할 수도 있다. 하지만 이제 우리는 <code>4.625</code>가 <code>기울기</code>라는 것을 안다. 다시 말해 <span class="math inline">\(X\)</span>가 한 단위 변화할때 <span class="math inline">\(Y\)</span>가 4.625만큼 증가한다는 것이다. 하지만 명목척도인 <span class="math inline">\(X\)</span>의 한 단위 변화량은 어떠한 의미도 없다. 먼저 <span class="math inline">\(X\)</span>의 절대값이 커지는 것에 의미가 있는가? A형에서 B형, O형으로의 변화가 의미가 있는가? 또한 한 단위의 변화, 다시 말해 A형-&gt;B형, 또는 B형 -&gt;O형으로의 변화가 의미가 있는가?</p>
<p>따라서 회귀분석에는 반드시 등간척도 이상의 변수만이 투입이 가능하다. 서열척도의 경우 방향이 있기 때문에 투입가능하다고 생각하지만, 1등과 2등, 2등과 3등의 차이가 일정하지 않기 때문에 <span class="math inline">\(X\)</span> 한단위 변화량의 의미가 없다.</p>
<p>[그림삽입]- 엑스축은 혈액형, 와이축은 성과
옉스축은 등수(등간X) 와이축은 성과 점수</p>
</div>
<div id="범주형-변수가-독립변수로-투입될-때" class="section level3 hasAnchor" number="8.4.2">
<h3><span class="header-section-number">8.4.2</span> 범주형 변수가 독립변수로 투입될 때<a href="intuitive.html#%EB%B2%94%EC%A3%BC%ED%98%95-%EB%B3%80%EC%88%98%EA%B0%80-%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EB%A1%9C-%ED%88%AC%EC%9E%85%EB%90%A0-%EB%95%8C" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>그렇다면 회귀분석에는 범주형 변수 투입이 불가능한가? 불가능하다기 보다는 우회하는 경로가 있다. ’종속변수(dependent variable, Y)’가 범주형 변수일 때는 ’로지스틱 회귀분석’을 실시해야하기 때문에 이 장에서는 다루지 않는다. ’독립변수(independent variables, Xs)’가 범주형 변수일때는 반드시 더미화해야 하며, 해석 또한 달라진다.</p>
<div id="이분형dichotomous-척도가-독립변수일-때" class="section level4 hasAnchor" number="8.4.2.1">
<h4><span class="header-section-number">8.4.2.1</span> 이분형(dichotomous) 척도가 독립변수일 때<a href="intuitive.html#%EC%9D%B4%EB%B6%84%ED%98%95dichotomous-%EC%B2%99%EB%8F%84%EA%B0%80-%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EC%9D%BC-%EB%95%8C" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>이분형 척도는 범주가 두 개인 척도를 의미한다. 대표적으로 성별(남/여), 취업/진학, 합격/불합격 등과 같은 변수가 이에 해당된다. 이분형 척도는 범주가 세 개 이상인 척도에 비해 다루기 쉬운 편이다.</p>
<p>이분형 척도는 범주가 두개 이므로 기준 범주는 ‘0’, 그리고 반대의 범주는 ’1로 코딩하는 것이 원칙이다. 아래 표와 같이 성별(남/여)이 직무성과에 미치는 영향을 확인하고 싶은 데이터가 있다고 가정해보자. 여성을 기준집단(0으로 코딩)으로 두고, 남성은 비교집단(1로 코딩)하였다.</p>
<table>
<thead>
<tr class="header">
<th align="center">ID</th>
<th align="center">X(성별)</th>
<th align="center">Y(직무성과)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">1</td>
<td align="center">1</td>
<td align="center">12</td>
</tr>
<tr class="even">
<td align="center">2</td>
<td align="center">1</td>
<td align="center">11</td>
</tr>
<tr class="odd">
<td align="center">3</td>
<td align="center">1</td>
<td align="center">18</td>
</tr>
<tr class="even">
<td align="center">4</td>
<td align="center">1</td>
<td align="center">19</td>
</tr>
<tr class="odd">
<td align="center">5</td>
<td align="center">1</td>
<td align="center">21</td>
</tr>
<tr class="even">
<td align="center">6</td>
<td align="center">0</td>
<td align="center">18.5</td>
</tr>
<tr class="odd">
<td align="center">7</td>
<td align="center">0</td>
<td align="center">21.5</td>
</tr>
<tr class="even">
<td align="center">8</td>
<td align="center">0</td>
<td align="center">23.5</td>
</tr>
<tr class="odd">
<td align="center">9</td>
<td align="center">0</td>
<td align="center">22.5</td>
</tr>
<tr class="even">
<td align="center">10</td>
<td align="center">0</td>
<td align="center">25</td>
</tr>
</tbody>
</table>
<pre><code>## 
## Call:
## lm(formula = Y ~ X, data = genderLearning)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
##  -5.20  -2.95   0.80   2.55   4.80 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   22.200      1.602  13.861 7.09e-07 ***
## X             -6.000      2.265  -2.649   0.0293 *  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 3.581 on 8 degrees of freedom
## Multiple R-squared:  0.4673, Adjusted R-squared:  0.4007 
## F-statistic: 7.018 on 1 and 8 DF,  p-value: 0.0293
## 
##  Welch Two Sample t-test
## 
## data:  Y by X
## t = 2.6491, df = 6.2143, p-value = 0.03683
## alternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0
## 95 percent confidence interval:
##   0.5038568 11.4961432
## sample estimates:
## mean in group 0 mean in group 1 
##            22.2            16.2</code></pre>
<p>회귀분석결과를 바탕으로 회귀식을 써보면 다음과 같다.
<span class="math display">\[\hat{Y}(직무수행) = 22.200-6.000 \ast X(성별) \]</span></p>
<p>독립변수인 성별의 회귀계수는 ’-6.000’으로 부적인 영향관계를 갖고 있다. 1=남성, 0=여성으로 코딩했으므로 남성일수록 여성에 비해 직무수행 점수가 낮다고 해석할 수 있다. 좀더 선명한 해석을 하기 위해서는 독립변수 X에 집단을 직접 집어 넣어 <span class="math inline">\(\hat{Y}\)</span>을 산출하면 된다.</p>
<p>남성집단은 X=1 이므로, 예측되는 직무수행 점수는 16.200이다.<br />
<span class="math display">\[\hat{Y}(직무수행) = 22.200-6.000 \ast 1 = 16.200 \]</span>
여성집단은 X=0 이므로, 예측되는 직무수행 점수는 22.2000이다.
<span class="math display">\[\hat{Y}(직무수행) = 22.200-6.000 \ast 0 = 22.200 \]</span>
다시 회귀식을 살펴보면, 기준집단(x=0 )의 <span class="math inline">\(\hat{Y}\)</span>은 회귀식의 절편과 같고, 비교집단(x=1)의 <span class="math inline">\(\hat{Y}\)</span>은 기준집단과 회귀계수 만큼의 격차(differences)와 같다.</p>
</div>
<div id="집단-이상의-범주형-척도가-독립변수일-때" class="section level4 hasAnchor" number="8.4.2.2">
<h4><span class="header-section-number">8.4.2.2</span> 3집단 이상의 범주형 척도가 독립변수일 때<a href="intuitive.html#%EC%A7%91%EB%8B%A8-%EC%9D%B4%EC%83%81%EC%9D%98-%EB%B2%94%EC%A3%BC%ED%98%95-%EC%B2%99%EB%8F%84%EA%B0%80-%EB%8F%85%EB%A6%BD%EB%B3%80%EC%88%98%EC%9D%BC-%EB%95%8C" class="anchor-section" aria-label="Anchor link to header"></a></h4>
<p>이분변수인 경우 한 집단은 0, 다른 집단은 1로 코딩을 할 수 있기 때문에 두 집단의 격차(difference)로 회귀분석을 실시할 수 있지만, 3개 집단부터는 불가능하다. 따라서 3개의 집단을 쌍별 비교하는 ’더미코딩’을 실시해야 한다.</p>
<p>앞서 살펴봤던 혈액형과 직무수행과의 관계를 살펴보자. A형은 1, B형은 2, O형은 3으로 코딩되어 있다.더미코딩의 핵심은 n개의 집단을 ’n-1’개의 변수로 재코딩하는 것이다. 더미코딩을 하기 위해서는 기준집단(reference group)을 먼저 설정해야한다. 임의로 기준집단을 O형으로 두자. 3개의 범주는 n-1, 즉 2개의 더미변수를 추가로 생성해야 한다. 변수의 코딩은 아래의 표와 같다. 기준집단을 O형으로 두면, 추가되는 더미변수들은 각각 A형과 B형을 의미하게 된다.</p>
<table>
<thead>
<tr class="header">
<th align="center">X(혈액혈)</th>
<th align="center">D1(A형)</th>
<th align="center">D2(B형)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td align="center">1</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td align="center">0</td>
<td align="center">1</td>
</tr>
<tr class="odd">
<td align="center">O</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
</tbody>
</table>
<p>좀더 쉬운 이해를 위해 아래에 더미코딩이 추가된 데이터 셋을 살펴보자. 변수를 추가 한다는 말은 열(column)이 추가된다는 뜻이다. 기존에 X(혈액형) 변수는 하나의 열(column)이다. 더미변수를 두개 추가하였으므로, 2개의 column이 추가로 생성되었다. 데이터를 하나 하나 살펴보자. 각 행(row)은 사람, 열(column)은 변수를 의미함을 상기하자.</p>
<ul>
<li>A형인 사람은 D1변수에는 1, D2변수는 0의 값을 갖는다.</li>
<li>B형인 사람은 D1변수에는 0, D2변수는 1의 값을 갖는다.</li>
<li>O형인 사람은 D1변수에는 0, D2변수는 0의 값을 갖는다.</li>
</ul>
<p>이와 같이 n-1 개의 더미변수를 통해 3집단을 1 또는 0의 값을 갖도록 코딩할 수 있다.</p>
<div class="sourceCode" id="cb98"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb98-1"><a href="intuitive.html#cb98-1" tabindex="-1"></a>ID<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>,<span class="dv">3</span>,<span class="dv">4</span>,<span class="dv">5</span>,<span class="dv">6</span>,<span class="dv">7</span>,<span class="dv">8</span>,<span class="dv">9</span>,<span class="dv">10</span>) </span>
<span id="cb98-2"><a href="intuitive.html#cb98-2" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>)</span>
<span id="cb98-3"><a href="intuitive.html#cb98-3" tabindex="-1"></a>D1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb98-4"><a href="intuitive.html#cb98-4" tabindex="-1"></a>D2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="dv">0</span>, <span class="dv">0</span>)</span>
<span id="cb98-5"><a href="intuitive.html#cb98-5" tabindex="-1"></a>Y<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">11</span>, <span class="dv">14</span>, <span class="dv">15</span>, <span class="dv">19</span>, <span class="fl">20.5</span>, <span class="fl">18.5</span>, <span class="fl">18.5</span>, <span class="dv">27</span>, <span class="dv">25</span>)</span>
<span id="cb98-6"><a href="intuitive.html#cb98-6" tabindex="-1"></a>bloodLearning2 <span class="ot">&lt;-</span><span class="fu">data.frame</span>(ID, X, D1, D2, Y)</span>
<span id="cb98-7"><a href="intuitive.html#cb98-7" tabindex="-1"></a>bloodReg2 <span class="ot">&lt;-</span><span class="fu">lm</span>(Y <span class="sc">~</span> D1 <span class="sc">+</span> D2, <span class="at">data=</span>bloodLearning2)</span>
<span id="cb98-8"><a href="intuitive.html#cb98-8" tabindex="-1"></a>bloodLearning2</span>
<span id="cb98-9"><a href="intuitive.html#cb98-9" tabindex="-1"></a><span class="do">##    ID X D1 D2    Y</span></span>
<span id="cb98-10"><a href="intuitive.html#cb98-10" tabindex="-1"></a><span class="do">## 1   1 1  1  0 12.0</span></span>
<span id="cb98-11"><a href="intuitive.html#cb98-11" tabindex="-1"></a><span class="do">## 2   2 1  1  0 11.0</span></span>
<span id="cb98-12"><a href="intuitive.html#cb98-12" tabindex="-1"></a><span class="do">## 3   3 1  1  0 14.0</span></span>
<span id="cb98-13"><a href="intuitive.html#cb98-13" tabindex="-1"></a><span class="do">## 4   4 1  1  0 15.0</span></span>
<span id="cb98-14"><a href="intuitive.html#cb98-14" tabindex="-1"></a><span class="do">## 5   5 2  0  1 19.0</span></span>
<span id="cb98-15"><a href="intuitive.html#cb98-15" tabindex="-1"></a><span class="do">## 6   6 2  0  1 20.5</span></span>
<span id="cb98-16"><a href="intuitive.html#cb98-16" tabindex="-1"></a><span class="do">## 7   7 2  0  1 18.5</span></span>
<span id="cb98-17"><a href="intuitive.html#cb98-17" tabindex="-1"></a><span class="do">## 8   8 2  0  1 18.5</span></span>
<span id="cb98-18"><a href="intuitive.html#cb98-18" tabindex="-1"></a><span class="do">## 9   9 3  0  0 27.0</span></span>
<span id="cb98-19"><a href="intuitive.html#cb98-19" tabindex="-1"></a><span class="do">## 10 10 3  0  0 25.0</span></span>
<span id="cb98-20"><a href="intuitive.html#cb98-20" tabindex="-1"></a><span class="fu">summary</span>(bloodReg2)</span>
<span id="cb98-21"><a href="intuitive.html#cb98-21" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb98-22"><a href="intuitive.html#cb98-22" tabindex="-1"></a><span class="do">## Call:</span></span>
<span id="cb98-23"><a href="intuitive.html#cb98-23" tabindex="-1"></a><span class="do">## lm(formula = Y ~ D1 + D2, data = bloodLearning2)</span></span>
<span id="cb98-24"><a href="intuitive.html#cb98-24" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb98-25"><a href="intuitive.html#cb98-25" tabindex="-1"></a><span class="do">## Residuals:</span></span>
<span id="cb98-26"><a href="intuitive.html#cb98-26" tabindex="-1"></a><span class="do">##     Min      1Q  Median      3Q     Max </span></span>
<span id="cb98-27"><a href="intuitive.html#cb98-27" tabindex="-1"></a><span class="do">## -2.0000 -0.9062 -0.3750  1.0000  2.0000 </span></span>
<span id="cb98-28"><a href="intuitive.html#cb98-28" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb98-29"><a href="intuitive.html#cb98-29" tabindex="-1"></a><span class="do">## Coefficients:</span></span>
<span id="cb98-30"><a href="intuitive.html#cb98-30" tabindex="-1"></a><span class="do">##             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb98-31"><a href="intuitive.html#cb98-31" tabindex="-1"></a><span class="do">## (Intercept)   26.000      1.024   25.38 3.76e-08 ***</span></span>
<span id="cb98-32"><a href="intuitive.html#cb98-32" tabindex="-1"></a><span class="do">## D1           -13.000      1.254  -10.36 1.69e-05 ***</span></span>
<span id="cb98-33"><a href="intuitive.html#cb98-33" tabindex="-1"></a><span class="do">## D2            -6.875      1.254   -5.48 0.000926 ***</span></span>
<span id="cb98-34"><a href="intuitive.html#cb98-34" tabindex="-1"></a><span class="do">## ---</span></span>
<span id="cb98-35"><a href="intuitive.html#cb98-35" tabindex="-1"></a><span class="do">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb98-36"><a href="intuitive.html#cb98-36" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb98-37"><a href="intuitive.html#cb98-37" tabindex="-1"></a><span class="do">## Residual standard error: 1.449 on 7 degrees of freedom</span></span>
<span id="cb98-38"><a href="intuitive.html#cb98-38" tabindex="-1"></a><span class="do">## Multiple R-squared:  0.9407, Adjusted R-squared:  0.9238 </span></span>
<span id="cb98-39"><a href="intuitive.html#cb98-39" tabindex="-1"></a><span class="do">## F-statistic: 55.53 on 2 and 7 DF,  p-value: 5.075e-05</span></span></code></pre></div>
<p>더미코딩이 완료되면, 더미변수만을 회귀식에 투입하면 된다. 이때 회귀식은 <span class="math inline">\(Y=B0+B1*D1+B2+D2+e\)</span>이다. 회귀분석결과 3개의 계수가 산출되었다.</p>
<ul>
<li>Y절편 : 26.000</li>
<li>D1의 회귀계수 : -13.000</li>
<li>D2의 회귀계수 : -6.875</li>
</ul>
<p>이 계수들을 활용하여 회귀식을 다시 써보자.</p>
<p><span class="math display">\[ \hat{Y}= 26.000-13.000\ast D1 -6.875\ast D2 \]</span>
Y절편은 D1과 D2가 모두 0일때 Y값이므로, O형의 직무수행점수이다. (O형은 D1과 D2에 모두 0으로 코딩한 집단이라는 것을 기억하자). 따라서 O형의 직무수행점수는 26점이다.
D1의 회귀 계수는 D1이 1일때와 0일때의 격차이다.</p>
<ul>
<li>D1이 1일때 (동시에 D2은 0) : 26.000-13.000<em>1-6.875</em>0 = 13.000 -&gt; A형의 직무수행점수</li>
<li>D1이 0일때 (동시에 D2은 0) : 26.000-13.000<em>0-6.875</em>0 = 26.000 -&gt;O형의 직무수행점수</li>
</ul>
<p>따라서 D1의 회귀계수(-13.000)를 통해, A형과 O형의 직무수행점수의 차이가 -13.000임을 알 수 있다.</p>
<p>마찬가지로 D2의 회귀 계수는 D2가 1일때 (B형)와 D2가 0일때 (O형)의 직무수행점수의 차이를 의미한다. 헷갈릴때는 각각의 변수에 값을 투입해보면 정확히 이해할 수 있다.</p>
<ul>
<li>D2이 1일때 (동시에 D1은 0) : 26.000-13.000<em>0-6.875</em>1 = 19.125 -&gt; B형의 직무수행점수</li>
<li>D2이 0일때 (동시에 D1은 0) : 26.000-13.000<em>0-6.875</em>0 = 26.000 -&gt; O형의 직무수행점수</li>
</ul>
<p>이처럼 더미변수를 투입한 회귀식에서의 회귀계수는 준거집단-비교집단의 차이(difference)를 의미한다. 또한</p>
<p>barplot(height=data<span class="math inline">\(value, names=data\)</span>name)</p>
<p>[그래프 추가]</p>
<p><img src="_main_files/figure-html/unnamed-chunk-113-1.png" alt="" width="672" /></p>
</div>
</div>
</div>
<div id="회귀식으로-이해하는-조절효과" class="section level2 hasAnchor" number="8.5">
<h2><span class="header-section-number">8.5</span> 회귀식으로 이해하는 조절효과<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EC%A1%B0%EC%A0%88%ED%9A%A8%EA%B3%BC" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="조절효과의-개념" class="section level3 hasAnchor" number="8.5.1">
<h3><span class="header-section-number">8.5.1</span> 조절효과의 개념<a href="intuitive.html#%EC%A1%B0%EC%A0%88%ED%9A%A8%EA%B3%BC%EC%9D%98-%EA%B0%9C%EB%85%90" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>조절효과는 ’moderation effect’라고 불리우며, Y 와 X의 관계를 조절변수(M)이 변화 시키는 것을 의미한다. 조절효과는 앞서 살펴본 2차 회귀식을 제대로 이해했다면 아주 손쉽게 이해할 수 있다. 2차 회귀식의 핵심은 Y와 X의 관계, 즉 기울기가 일정하지 않고 ’변화’한다는 것이었다. 마찬가지로 조절효과는 어떠한 조절 변수에 의해 Y와 X의 관계, 즉 기울기(회귀계수)가 변화한다는 것을 의미한다.</p>
<p>산업인력개발 장면에서 조절효과분석이 필요한 사례는 쉽게 샆려볼 수 있다. 앞서 살펴본 학습시간(X)과 직무수행점수(Y)의 관계를 떠올려보자. 가장 기본적인 회귀식은 학습시간이 한 단위 증가할때, 직무수행 점수가 <code>일정하게</code> 증가한다는 것이다. 그러나 모든 사람이 학습시간을 늘릴수록 똑같은 속도로 직무수행시간이 늘어나지는 않는다. 예를 들어 ’일 열의’라는 구인을 생각해보자. 많은 동기이론들을 통해 자신의 직무 및 일에 동기를 갖고 열의를 갖는 사람들일 수록 학습효과가 높다고 밝혀져있다. 따라서 우리는 다음과 같은 가설을 생각해볼 수 있다.</p>
<ul>
<li>가설 1: 학습시간(X)이 늘어날 수록 직무수행점수(Y)는 늘어날 것이다.</li>
<li>가설 2: 일 열의(M)가 높은 사람일 수록 학습시간(X)이 직무수행점수(Y)에 미치는 정적인 영향은 증가(강화)할 것이다.</li>
</ul>
<p>직관적으로 생각해보면, 일 열의가 높은 집단과 낮은 집단을 구분하여 회귀선을 그려보면</p>
<ul>
<li>일 열의가 높은 집단은 X와 Y의 그래프가 좀더 가파를 것이다(기울기의 절대값이 크다)</li>
<li>일 열의가 낮은 집단은 X와 Y의 그래프가 좀더 완만할 것이다(기울기의 절대값이 작다)</li>
</ul>
<p>따라서 조절효과의 핵심은 X가 Y에 미치는 <code>영향</code>이 M의 크기에 따라 <code>변화</code>한다는 점이다.</p>
</div>
<div id="회귀식-만들기와-해석하기" class="section level3 hasAnchor" number="8.5.2">
<h3><span class="header-section-number">8.5.2</span> 회귀식 만들기와 해석하기<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D-%EB%A7%8C%EB%93%A4%EA%B8%B0%EC%99%80-%ED%95%B4%EC%84%9D%ED%95%98%EA%B8%B0" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>조절효과를 분석하기 위한 기본적인 회귀식은 다음과 같다.</p>
<p><span class="math display" id="eq:moderation">\[\begin{equation}
Y= B_{0}+B_{1} \ast X+ B_{2} \ast M + B_{3} \ast X_{1} \ast M + e
\tag{8.6}
\end{equation}\]</span></p>
<p>회귀식은 크게 네개의 파트로 구성되어 있다: (1) Y절편, (2) 독립변수<span class="math inline">\(X\)</span>의 회귀계수, (3) 조절변수 <span class="math inline">\(M\)</span>의 회귀계수, (4) 독립변수 <span class="math inline">\(X\)</span>와 조절변수<span class="math inline">\(Y\)</span>의 곱(<code>interaction term</code>) 의 회귀계수. 이러한 기본 형태에서는 왜 <span class="math inline">\(B_{3}\)</span>가 조절효과를 나타내는지 이해하기가 어렵다. 따라서 이 회귀식을 <a href="intuitive.html#eq:moderation1">(8.7)</a>과 같이 변형해보자.</p>
<p><span class="math display" id="eq:moderation1">\[\begin{equation}
\begin{split}
Y &amp; = B_{0}+B_{1} \ast X+ B_{2} \ast M + B_{3} \ast X \ast M + e\\
&amp; = B_{0} +(B_{1}+B_{3}\ast M) \ast X + B_2 \ast M\\
\end{split}
\tag{8.7}
\end{equation}\]</span></p>
<p><a href="intuitive.html#eq:moderation1">(8.7)</a>에서 주목해야할 부분은 <span class="math inline">\(X\)</span>의 회귀계수인 <code>$B_{1}+B_{3} \ast M$</code>이다. <span class="math inline">\(X\)</span>가 <span class="math inline">\(Y\)</span>에 미치는 영향력인 회귀계수가 하나의 값으로 추정되는 것이 아니라 조절변수<span class="math inline">\(M\)</span>이 포함된 회귀식의 형태를 띈다. 따라서 조절효과분석은 regression-in-regression, 다시 말해 회귀분석 안에 또하나의 회귀식이 있는 형태를 띈다.</p>
<p><code>$B_{1}+B_{3} \ast M$</code>는 X가 Y에 미치는 회귀계수를 종속변수로 하고, M을 독립변수로 하는 또하나의 회귀식인 것이다. 앞서 언급한 <code>가설 2: 일 열의(M)가 높은 사람일 수록 학습시간(X)이 직무수행점수(Y)에 미치는 정적인 영향은 증가(강화)할 것이다</code>가 바로 이 회귀식을 의미한다. 가설을 찬찬히 살펴보면 영향을 받는 쪽(종속변수)는 X와 Y의 기울기이고, 영향을 주는 쪽(독립변수)는 일 열의(M)이다.</p>
</div>
<div id="분석결과-해석-예제" class="section level3 hasAnchor" number="8.5.3">
<h3><span class="header-section-number">8.5.3</span> 분석결과 해석 예제<a href="intuitive.html#%EB%B6%84%EC%84%9D%EA%B2%B0%EA%B3%BC-%ED%95%B4%EC%84%9D-%EC%98%88%EC%A0%9C" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>실제 데이터를 활용하여 조절효과를 분석해보자. 이번에는 20명의 사람의 학습시간(X), 일 열의(M), 직무수행점수(Y)의 데이터를 수집했다. 우리가 수집한 데이터는 행이 20개(사례수), 열이 4개 (ID를 포함하여 변수 4개)의 20 * 4 의 매트릭스 형태이다.</p>
<p>조절효과의 기본 회귀식을 생각해보면 변수 하나가 더 필요하다. <code>X * M</code> , 즉 독립변수와 조절변수의 상호작용항이다. 여러가지 방법이 있지만 통상적으로는 데이터 프레임에 이 상호작용항을 새로운 변수로 추가한다. R에서는 기존 변수(old variable)을 연산하여 새로운 변수(new variable) 로 간단히 추가할 수 있다. 아래 R 코드를 보면 moderLearning<span class="math inline">\(XM &lt;-moderLearning\)</span>X * moderLearning$M 의 구분이 X과 M을 곱하여 XM을 만들고 있다. 최종적으로 만들어진 데이터프레임은 변수 열이 추가되어 20*5의 행렬이다.</p>
<div class="sourceCode" id="cb99"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb99-1"><a href="intuitive.html#cb99-1" tabindex="-1"></a>ID<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">20</span>) </span>
<span id="cb99-2"><a href="intuitive.html#cb99-2" tabindex="-1"></a>X<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">1</span>, <span class="fl">0.5</span>, <span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">3</span>, <span class="fl">3.5</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="fl">4.5</span>, <span class="dv">5</span>, <span class="fl">1.2</span>, <span class="fl">0.7</span>, <span class="fl">2.2</span>, <span class="fl">3.3</span>, <span class="fl">3.1</span>, <span class="fl">3.7</span>, <span class="fl">4.1</span>, <span class="fl">3.9</span>, <span class="fl">4.3</span>, <span class="dv">5</span>)</span>
<span id="cb99-3"><a href="intuitive.html#cb99-3" tabindex="-1"></a>M<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">1</span>, <span class="fl">1.2</span>, <span class="dv">1</span>, <span class="dv">1</span>, <span class="fl">1.1</span>, <span class="dv">1</span>, <span class="fl">1.5</span>, <span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">5</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">7</span>, <span class="dv">6</span>, <span class="dv">7</span>, <span class="dv">4</span>, <span class="dv">5</span>)</span>
<span id="cb99-4"><a href="intuitive.html#cb99-4" tabindex="-1"></a>Y<span class="ot">&lt;-</span><span class="fu">c</span>(<span class="dv">12</span>, <span class="dv">11</span>, <span class="dv">18</span>, <span class="dv">19</span>, <span class="dv">21</span>, <span class="fl">18.5</span>, <span class="fl">21.5</span>, <span class="fl">23.5</span>, <span class="fl">22.5</span>, <span class="dv">25</span>, <span class="dv">12</span>, <span class="dv">11</span>, <span class="dv">18</span>, <span class="dv">19</span>, <span class="dv">28</span>, <span class="dv">29</span>, <span class="dv">26</span>, <span class="fl">27.5</span>, <span class="fl">27.5</span>, <span class="dv">30</span>)</span>
<span id="cb99-5"><a href="intuitive.html#cb99-5" tabindex="-1"></a>moderLearning <span class="ot">&lt;-</span><span class="fu">data.frame</span>(ID, X1, M, Y)</span>
<span id="cb99-6"><a href="intuitive.html#cb99-6" tabindex="-1"></a>moderLearning<span class="sc">$</span>XM <span class="ot">&lt;-</span>moderLearning<span class="sc">$</span>X <span class="sc">*</span> moderLearning<span class="sc">$</span>M </span>
<span id="cb99-7"><a href="intuitive.html#cb99-7" tabindex="-1"></a>moderLearning</span>
<span id="cb99-8"><a href="intuitive.html#cb99-8" tabindex="-1"></a><span class="do">##    ID  X1   M    Y    XM</span></span>
<span id="cb99-9"><a href="intuitive.html#cb99-9" tabindex="-1"></a><span class="do">## 1   1 1.0 2.0 12.0  2.00</span></span>
<span id="cb99-10"><a href="intuitive.html#cb99-10" tabindex="-1"></a><span class="do">## 2   2 0.5 1.0 11.0  0.50</span></span>
<span id="cb99-11"><a href="intuitive.html#cb99-11" tabindex="-1"></a><span class="do">## 3   3 2.0 1.2 18.0  2.40</span></span>
<span id="cb99-12"><a href="intuitive.html#cb99-12" tabindex="-1"></a><span class="do">## 4   4 3.0 1.0 19.0  3.00</span></span>
<span id="cb99-13"><a href="intuitive.html#cb99-13" tabindex="-1"></a><span class="do">## 5   5 3.0 1.0 21.0  3.00</span></span>
<span id="cb99-14"><a href="intuitive.html#cb99-14" tabindex="-1"></a><span class="do">## 6   6 3.5 1.1 18.5  3.85</span></span>
<span id="cb99-15"><a href="intuitive.html#cb99-15" tabindex="-1"></a><span class="do">## 7   7 4.0 1.0 21.5  4.00</span></span>
<span id="cb99-16"><a href="intuitive.html#cb99-16" tabindex="-1"></a><span class="do">## 8   8 4.0 1.5 23.5  6.00</span></span>
<span id="cb99-17"><a href="intuitive.html#cb99-17" tabindex="-1"></a><span class="do">## 9   9 4.5 1.0 22.5  4.50</span></span>
<span id="cb99-18"><a href="intuitive.html#cb99-18" tabindex="-1"></a><span class="do">## 10 10 5.0 2.0 25.0 10.00</span></span>
<span id="cb99-19"><a href="intuitive.html#cb99-19" tabindex="-1"></a><span class="do">## 11 11 1.0 5.0 12.0  5.00</span></span>
<span id="cb99-20"><a href="intuitive.html#cb99-20" tabindex="-1"></a><span class="do">## 12 12 0.5 7.0 11.0  3.50</span></span>
<span id="cb99-21"><a href="intuitive.html#cb99-21" tabindex="-1"></a><span class="do">## 13 13 2.0 7.0 18.0 14.00</span></span>
<span id="cb99-22"><a href="intuitive.html#cb99-22" tabindex="-1"></a><span class="do">## 14 14 3.0 6.0 19.0 18.00</span></span>
<span id="cb99-23"><a href="intuitive.html#cb99-23" tabindex="-1"></a><span class="do">## 15 15 3.0 7.0 28.0 21.00</span></span>
<span id="cb99-24"><a href="intuitive.html#cb99-24" tabindex="-1"></a><span class="do">## 16 16 3.5 7.0 29.0 24.50</span></span>
<span id="cb99-25"><a href="intuitive.html#cb99-25" tabindex="-1"></a><span class="do">## 17 17 4.0 6.0 26.0 24.00</span></span>
<span id="cb99-26"><a href="intuitive.html#cb99-26" tabindex="-1"></a><span class="do">## 18 18 4.0 7.0 27.5 28.00</span></span>
<span id="cb99-27"><a href="intuitive.html#cb99-27" tabindex="-1"></a><span class="do">## 19 19 4.5 4.0 27.5 18.00</span></span>
<span id="cb99-28"><a href="intuitive.html#cb99-28" tabindex="-1"></a><span class="do">## 20 20 5.0 5.0 30.0 25.00</span></span>
<span id="cb99-29"><a href="intuitive.html#cb99-29" tabindex="-1"></a>moderReg <span class="ot">&lt;-</span><span class="fu">lm</span>(Y <span class="sc">~</span> X<span class="sc">+</span>M<span class="sc">+</span> XM, <span class="at">data=</span>moderLearning)</span>
<span id="cb99-30"><a href="intuitive.html#cb99-30" tabindex="-1"></a><span class="fu">summary</span>(moderReg)</span>
<span id="cb99-31"><a href="intuitive.html#cb99-31" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb99-32"><a href="intuitive.html#cb99-32" tabindex="-1"></a><span class="do">## Call:</span></span>
<span id="cb99-33"><a href="intuitive.html#cb99-33" tabindex="-1"></a><span class="do">## lm(formula = Y ~ X + M + XM, data = moderLearning)</span></span>
<span id="cb99-34"><a href="intuitive.html#cb99-34" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb99-35"><a href="intuitive.html#cb99-35" tabindex="-1"></a><span class="do">## Residuals:</span></span>
<span id="cb99-36"><a href="intuitive.html#cb99-36" tabindex="-1"></a><span class="do">##     Min      1Q  Median      3Q     Max </span></span>
<span id="cb99-37"><a href="intuitive.html#cb99-37" tabindex="-1"></a><span class="do">## -4.2673 -0.9477 -0.4419  1.0102  4.4372 </span></span>
<span id="cb99-38"><a href="intuitive.html#cb99-38" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb99-39"><a href="intuitive.html#cb99-39" tabindex="-1"></a><span class="do">## Coefficients:</span></span>
<span id="cb99-40"><a href="intuitive.html#cb99-40" tabindex="-1"></a><span class="do">##             Estimate Std. Error t value Pr(&gt;|t|)    </span></span>
<span id="cb99-41"><a href="intuitive.html#cb99-41" tabindex="-1"></a><span class="do">## (Intercept)  10.8869     1.9740   5.515  4.7e-05 ***</span></span>
<span id="cb99-42"><a href="intuitive.html#cb99-42" tabindex="-1"></a><span class="do">## X             2.3572     0.6012   3.921  0.00122 ** </span></span>
<span id="cb99-43"><a href="intuitive.html#cb99-43" tabindex="-1"></a><span class="do">## M            -0.4978     0.4213  -1.182  0.25457    </span></span>
<span id="cb99-44"><a href="intuitive.html#cb99-44" tabindex="-1"></a><span class="do">## XM            0.4216     0.1357   3.106  0.00679 ** </span></span>
<span id="cb99-45"><a href="intuitive.html#cb99-45" tabindex="-1"></a><span class="do">## ---</span></span>
<span id="cb99-46"><a href="intuitive.html#cb99-46" tabindex="-1"></a><span class="do">## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1</span></span>
<span id="cb99-47"><a href="intuitive.html#cb99-47" tabindex="-1"></a><span class="do">## </span></span>
<span id="cb99-48"><a href="intuitive.html#cb99-48" tabindex="-1"></a><span class="do">## Residual standard error: 2.068 on 16 degrees of freedom</span></span>
<span id="cb99-49"><a href="intuitive.html#cb99-49" tabindex="-1"></a><span class="do">## Multiple R-squared:  0.9053, Adjusted R-squared:  0.8876 </span></span>
<span id="cb99-50"><a href="intuitive.html#cb99-50" tabindex="-1"></a><span class="do">## F-statistic:    51 on 3 and 16 DF,  p-value: 2.062e-08</span></span></code></pre></div>
<p>분석결과 X(학습시간)과 XM(학습시간 * 일열의)가 Y(직무수행점수)에 유의미한 영향을 미치는 것으로 나타났다. 구체적으로 해석하기 위해서 추정된 회귀계수를 활용하여 회귀식을 구성해보자.</p>
<p><span class="math display">\[ \hat{Y} = 10.8737 + 2.3928 \ast X -0.5915 \ast M + 0.4309 \ast XM \]</span>
<span class="math display">\[ \hat{Y} = 10.8737 + (2.3928+0.4309 \ast M) \ast X -0.5915 \ast M \]</span>
* Y 절편 : X(학습시간)과 M(일열의)가 0인 경우 Y(직무수행점수)가 10.8737 이다.</p>
<ul>
<li><p>M의 회귀계수 : X(학습시간)이 0일때, M(직무 열의)가 한 단위 증가할때 Y(직무수행점수)는 0.5915만큼 감소한다. 다만 통계적으로 유의지하지 않다(이는 M의 회귀계수 H1:<span class="math inline">\(B_{3}\)</span> is not equal to zero 가 기각되었음을 의미한다)</p></li>
<li><p>X의 회귀계수 : 2.3928+0.4309*M</p>
<ul>
<li>X의 회귀계수는 M에 따라 변화한다.</li>
<li>M=0일때 X가 한단위 변화할때 Y는 2.3928만큼 커진다 (2.3928 +0.4309*0)</li>
<li>M이 한단위 커질 수록 X의 Y에 대한 기울기는 0.4309 만큼 커진다.</li>
<li>예를 들어 M=1일때 X의 기울기는 2.3928+0.4309(purple), M=2(blue)일때 X의 기울기는 2.3928+0.4309*2이다.</li>
<li>거꾸로 X가 Y에 미치는 영향이 0인 점도 찾을 수 있다. 2.3928+0.4309*M=0을 풀면, M=-5.553 이다. 이는 M이 -5.553인 집단은 X와 Y의 관계가 0이라는 것을 뜻한다.</li>
</ul></li>
</ul>
<p><img src="_main_files/figure-html/unnamed-chunk-115-1.png" alt="" width="672" /></p>
</div>
</div>
<div id="회귀식으로-이해하는-매개효과" class="section level2 hasAnchor" number="8.6">
<h2><span class="header-section-number">8.6</span> 회귀식으로 이해하는 매개효과<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D%EC%9C%BC%EB%A1%9C-%EC%9D%B4%ED%95%B4%ED%95%98%EB%8A%94-%EB%A7%A4%EA%B0%9C%ED%9A%A8%EA%B3%BC" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="매개효과의-개념" class="section level3 hasAnchor" number="8.6.1">
<h3><span class="header-section-number">8.6.1</span> 매개효과의 개념<a href="intuitive.html#%EB%A7%A4%EA%B0%9C%ED%9A%A8%EA%B3%BC%EC%9D%98-%EA%B0%9C%EB%85%90" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="회귀식-만들기와-해석하기-1" class="section level3 hasAnchor" number="8.6.2">
<h3><span class="header-section-number">8.6.2</span> 회귀식 만들기와 해석하기<a href="intuitive.html#%ED%9A%8C%EA%B7%80%EC%8B%9D-%EB%A7%8C%EB%93%A4%EA%B8%B0%EC%99%80-%ED%95%B4%EC%84%9D%ED%95%98%EA%B8%B0-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
</div>
<div id="분석결과-해석-예제-1" class="section level3 hasAnchor" number="8.6.3">
<h3><span class="header-section-number">8.6.3</span> 분석결과 해석 예제<a href="intuitive.html#%EB%B6%84%EC%84%9D%EA%B2%B0%EA%B3%BC-%ED%95%B4%EC%84%9D-%EC%98%88%EC%A0%9C-1" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>’가설 1: 학습시간(X)이 늘어날 수록 직무수행점수(Y)는 늘어날 것이다’을 회귀식으로 써보면 다음 <a href="intuitive.html#eq:moderation1">(8.7)</a>과 같다. 이제는 y=a+bx의 회귀식이 눈에 익었을 것이라 생각한다. 이제는 회귀식을 쓸때 하나의 규칙을 더하도록 하겠다. y 절편은 항상 <span class="math inline">\(B_{0}\)</span>으로 1번째 독립변수(<span class="math inline">\(X_{1}\)</span>)의 회귀계수는 <span class="math inline">\(B_{1}\)</span>, 2번째 독립변수(<span class="math inline">\(X_{2}\)</span>)의 회귀계수는 <span class="math inline">\(B_{2}\)</span>, n번째 독립변수(<span class="math inline">\(X_{n}\)</span>)의 회귀계수는 <span class="math inline">\(B_{n}\)</span>으로 작성하도록 한다.</p>

</div>
</div>
</div>
<div class="footnotes">
<hr />
<ol start="5">
<li id="fn5"><p>1차 함수의 기울기도 미분의 방식으로 생각해보면 이해에 도움이 된다. <span class="math inline">\(Y=3x+10\)</span>을 미분하면, 기울기는 3인 상수이다. 직선인 1차함수의 그래프를 생각해보면 x의 값에 관계없이 기울기가 일정하다<a href="intuitive.html#fnref5" class="footnote-back">↩︎</a></p></li>
</ol>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="correlation.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="regression.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
  "sharing": {
    "github": false,
    "facebook": true,
    "twitter": true,
    "linkedin": false,
    "weibo": false,
    "instapaper": false,
    "vk": false,
    "whatsapp": false,
    "all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
  },
  "fontsettings": {
    "theme": "white",
    "family": "sans",
    "size": 2
  },
  "edit": {
    "link": "https://github.com/USERNAME/REPO/edit/BRANCH/08-intuitive.Rmd",
    "text": "Edit"
  },
  "history": {
    "link": null,
    "text": null
  },
  "view": {
    "link": null,
    "text": null
  },
  "download": ["_main.pdf", "_main.epub"],
  "search": {
    "engine": "fuse",
    "options": null
  },
  "toc": {
    "collapse": "subsection"
  }
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
